### ISSUE TITLE
Missing table column after parsing 

### ISSUE THREAD

**Issue by guillaume-millot** [run-llama/llama_parse#100]
I've parsed the following PDF one-pager.
[ENI_2018_p16.pdf](https://github.com/run-llama/llama_parse/files/14648388/ENI_2018_p16.pdf)

Here's the parsing results for the first table:
<img width="573" alt="image" src="https://github.com/run-llama/llama_parse/assets/90203812/8c67a27e-f573-42c5-b1af-3f9546cfaadd">

As you can see one column is missing:
![image](https://github.com/run-llama/llama_parse/assets/90203812/052a54db-935e-4924-951d-01818d827cb8)

It seems Unstructured is doing a slightly better job:
![image](https://github.com/run-llama/llama_parse/assets/90203812/f842f394-6fa9-420d-91cd-b83d8263c3b4)

**Comment by BinaryBrain** [comment]
Should be fix with the latest API release
