### ISSUE TITLE
Table parsing issue with multiple tables in close proximity

### ISSUE THREAD

**Issue by Starforged** [run-llama/llama_parse#102]
The Parsing of multiple tables in close proximity fails. The titles (or descriptions) of tables are deleted as well.

This is the input:
[chemiebuch_066-067_llamaparse.pdf](https://github.com/run-llama/llama_parse/files/14651095/chemiebuch_066-067_llamaparse.pdf)
The output:
[chemiebuch_066-067_llamaparse.txt](https://github.com/run-llama/llama_parse/files/14651099/chemiebuch_066-067_llamaparse.txt)
Here I have manually corrected the output to show how it should look:
[chemiebuch_066-067_llamaparse_corrected.txt](https://github.com/run-llama/llama_parse/files/14651101/chemiebuch_066-067_llamaparse_corrected.txt)

**Comment by BinaryBrain** [comment]
Should be fix with the latest API release
