### ISSUE TITLE
Timed Out Session/ Not getting result.

### ISSUE THREAD

**Issue by salujav4** [run-llama/llama_parse#108]
Making a call to your Llamaparse REST API, but the pdfs are not getting a uploaded, Any file, from 2mb to 25mb taking around 1 hour and after that the custom timer declines the request and gives Timeout error, I don't know if it is an error just surrounding my API key.  

These are the two endpoints in which I am making the call:
api.cloud.llamaindex.ai/api/parsing/upload
api.cloud.llamaindex.ai/api/parsing/job/<job_id>/result/markdown

**Comment by httplups** [comment]
I am having the same error. It was working for the same PDF when I used a different docker container. Which version are you using of Llama Parse and Llama Index?

**Comment by salujav4** [comment]
Hey, My issue has been resolved. Just change the 1st endpoint to:
https://cloud.llamaindex.ai/api/parsing
