### ISSUE TITLE
New FS not supported by llama-parse

### ISSUE THREAD

**Issue by thiagosalvatore** [run-llama/llama_parse#116]
llama-index now allow us to use Python FS (`AbstractFileSystem`) to load files so they don't need to exist in the local disk.

I couldn't find a way to make it work with llama-parse because it expects a path to a local file.

Are there any plans to make it possible?

### Error

`LlamaParse.load_data() got an unexpected keyword argument 'fs'. Skipping...`

**Comment by alarcon7a** [comment]
any updates with this?

**Comment by molihnv** [comment]
Hi, i'm facing the same issue. I cannot integrate LLamaParse with S3 loader, which makes no sense. Any updates?

**Comment by rohanprashant12** [comment]
Hi, any updates? S3 is very widely used and an important integration.

**Comment by eannam** [comment]
Hi, also encountering this issue, very frustrating.
