### ISSUE TITLE
LLama_Parse Returns a bunch of Undefined for my PDF

### ISSUE THREAD

**Issue by data-augur** [run-llama/llama_parse#119]
Hi,
I tried llama_parse with my PDF but it only returned a bunch of undefined. PDF is attached, 
[hubc1.pdf](https://github.com/run-llama/llama_parse/files/14761788/hubc1.pdf)

Following is the response I am getting.

[Document(id_='8ba2d447-b6da-4b12-afca-af8e140ab2dc', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, text='undefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined\n---\nundefined', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n')]

**Comment by sourabhdesai** [comment]
@data-augur sorry about that, we were experiencing a temporary issue on our end. Thanks for reporting it! Can you try again now?
