### ISSUE TITLE
LlamaParse demo notebook issue when using node parser

### ISSUE THREAD

**Issue by tituslhy** [run-llama/llama_parse#121]
Hello!

I was running the llama parse demo notebook in colab and I ran into a lot of traceback messages after running the following code:

```
from llama_index.core.node_parser import MarkdownElementNodeParser
from llama_parse import LlamaParse
import nest_asyncio
nest_asyncio.apply()

documents = LlamaParse(result_type="markdown").load_data("./uber_10q_march_2022.pdf")
node_parser = MarkdownElementNodeParser(llm=OpenAI(model="gpt-3.5-turbo-0125"), 
                                        num_workers=8)
nodes = node_parser.get_nodes_from_documents(documents)
```
The code still completed its run but the traceback messages appear to be pydantic related? Appending a screenshot of the error message, please.
![image](https://github.com/run-llama/llama_parse/assets/7207877/715292a7-3587-450b-b017-376c1f91d4fe)

**Comment by BinaryBrain** [comment]
This was fixed.
