### ISSUE TITLE
Unresponsive API call

### ISSUE THREAD

**Issue by mitalitavildar-se** [run-llama/llama_parse#123]
Using the standalone file parser. It was working fine until yesterday and suddenly became unresponsive. I tried creating a new key and running, but is still unresponsive. Looks like its buffering, but the kernel gets stuck and becomes unresponsive.

**Comment by Alexander-Deleeck** [comment]
I have encountered the same issue. Tried with multiple different pdf's of varying sizes, but it keeps becoming unresponsive.
However, no problem at all with the web browser version!
