### ISSUE TITLE
[BUG] 413 Request Entity Too Large

### ISSUE THREAD

**Issue by chengyjonathan** [run-llama/llama_parse#125]
I was sending a couple hundred page pdf request.

The site says a 1000 page maximum.

But i get a 413 request entity too large error.

**Comment by hexapode** [comment]
We limit to 750pages, and 50Mb per PDF, how big are your files?

**Comment by chengyjonathan** [comment]
oh i see, i have one that is 300ish pages but 80mb, that's why.

would the best path be to split the pdf into two, parse them separately, and combine the output nodes?

**Comment by BinaryBrain** [comment]
Sorry for the long delay. Yes, you can definitely do what you describe. We plan on supporting larger documents in the future.
