### ISSUE TITLE
File extension case sensitive throws parsing error

### ISSUE THREAD

**Issue by ggjx22** [run-llama/llama_parse#127]
Hi there, may I know if you are considering support for file extensions which are case sensitive (e.g. .PDF, .DOC, etc.)?

Btw, the following error can be solved by simply renaming the file extension to `.pdf`

```
Error while parsing the file 'c:\Users\<path-to-data-source>\Invoice_52810.PDF': Currently, only the following file types are supported: ['.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.dotm', '.rtf', '.wps', '.wpd', '.sxw', '.stw', '.sxg', '.pages', '.mw', '.mcw', '.uot', '.uof', '.uos', '.uop', '.ppt', '.pptx', '.pot', '.pptm', '.potx', '.potm', '.key', '.odp', '.odg', '.otp', '.fopd', '.sxi', '.sti', '.epub']
Current file type: .PDF
Failed to load file [c:\Users\<path-to-data-source>\Invoice_52810.PDF](file:///C:/Users/<path-to-data-source>/Invoice_52810.PDF) with error: Currently, only the following file types are supported: ['.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.dotm', '.rtf', '.wps', '.wpd', '.sxw', '.stw', '.sxg', '.pages', '.mw', '.mcw', '.uot', '.uof', '.uos', '.uop', '.ppt', '.pptx', '.pot', '.pptm', '.potx', '.potm', '.key', '.odp', '.odg', '.otp', '.fopd', '.sxi', '.sti', '.epub']
Current file type: .PDF. Skipping...
```

**Comment by Jordanm37** [comment]
Hi, it seems to be the case that I am getting the same error. 

"Parsing files: 100%|██████████| 94/94 [00:00<00:00, 2550.72it/s]
Error while parsing the file 'Doc ID: 6b7d681b-846d-4b7b-91cd-78d69ba56c8f
Text: Core – Assistance with Social, Economic and Community
Participation   NDIS Pricing Arrangements and Price Limits 202 3-24
Version 1.3  (published 7/02/2024 )  Page 59 of 94 Participation in
Community, Social and Civic  Activities – High Intensity Supports
These support items enable a participant who requires High Intensity
Supports , to engage...': Currently, only the following file types are supported: ['.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.dotm', '.rtf', '.wps', '.wpd', '.sxw', '.stw', '.sxg', '.pages', '.mw', '.mcw', '.uot', '.uof', '.uos', '.uop', '.ppt', '.pptx', '.pot', '.pptm', '.potx', '.potm', '.key', '.odp', '.odg', '.otp', '.fopd', '.sxi', '.sti', '.epub']
Current file type: .
Error while parsing the file 'Doc ID: 4ced617d-fe8f-469e-b164-b491de36b970
Text: General Claiming Rules   NDIS Pricing Arrangements and Price
Limits 202 3-24 Version 1.3  (published 7/02/2024 )  Page 21 of 94
10_799_0133_5_3  Provider travel - non-labour costs  Each  $1.00
$1.00  $1.00   11_799_0110_7_3  Provider travel - non-labour costs
Each  $1.00  $1.00  $1.00   11_799_0117_7_3  Provider travel - non-
labour costs  Each...': Currently, only the following file types are supported: ['.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.dotm', '.rtf', '.wps', '.wpd', '.sxw', '.stw', '.sxg', '.pages', '.mw', '.mcw', '.uot', '.uof', '.uos', '.uop', '.ppt', '.pptx', '.pot', '.pptm', '.potx', '.potm', '.key', '.odp', '.odg', '.otp', '.fopd', '.sxi', '.sti', '.epub']
Current file type: .
Error while parsing the file 'Doc ID: 64876982-3824-4046-bbd3-dae1c6aa5e02
Text: Core – Assistance with Social, Economic and Community
Participation   NDIS Pricing Arrangements and Price Limits 202 3-24
Version 1.3  (published 7/02/2024 )  Page 60 of 94 This support item
is not subject to price limits. It should only be used to recover the
costs of the  participant’s attendance at the community social and
participation activ...': Currently, only the following file types are supported: ['.pdf', '.doc', '.docx', '.docm', '.dot', '.dotx', '.dotm', '.rtf', '.wps', '.wpd', '.sxw', '.stw', '.sxg', '.pages', '.mw', '.mcw', '.uot', '.uof', '.uos', '.uop', '.ppt', '.pptx', '.pot', '.pptm', '.potx', '.potm', '.key', '.odp', '.odg', '.otp', '.fopd', '.sxi', '.sti', '.epub']
Current file type: ."


```
try:
    docs_parsed = LlamaParse(result_type='markdown', parsing_instruction="This is a pricing guide for a company. ANY .au or seeming extensions are just emails or websites and should be ignored. Please parse the document and return the parsed document in markdown format.").load_data(docs)
    print(docs_parsed)
except Exception as e:
    print("Error:", e)
```
   
   Using 0.4.1

**Comment by ggjx22** [comment]
Tested the parser again with extension `.PDF`.  An empty list returned.
