### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by jswift24** [run-llama/llama_parse#14]
Dear Llama Parse team
I really enjoyed Jerry's presentation at the MLOps conference yesterday. This seems like an exciting project.

What metrics did you use to evaluate parse quality for complex tables? And, how did Llama Parse do on these metrics vs the incumbents?

Thanks!

**Comment by hexapode** [comment]
We evaluate end to end the ability of LlamaParse + Recursive retrieval to correctly answer questions on table. Our end goal is to prepare data to RAG. More info should be released soon.
