### ISSUE TITLE
Return Error parsing PDF

### ISSUE THREAD

**Issue by kangtsang** [run-llama/llama_parse#145]
![image](https://github.com/run-llama/llama_parse/assets/72589730/23612328-dff2-4695-81fa-804207e97469)

pdf file
[financail-HK-00981-2023-FY.pdf](https://github.com/run-llama/llama_parse/files/14993818/financail-HK-00981-2023-FY.pdf)

**Comment by BinaryBrain** [comment]
It's working fine now apparently:

![Screenshot_20240709_121542](https://github.com/run-llama/llama_parse/assets/1102077/6bdf511e-ebe8-40b6-b533-011bb3b2eeb7)

Also, we have more meaningful errors now.
