### ISSUE TITLE
CORS issue when trying to upgrade llamaparse plan

### ISSUE THREAD

**Issue by quentin-r37** [run-llama/llama_parse#147]
When clicking on "Upgrade Plan" in [llama cloud](https://cloud.llamaindex.ai/parse)
![image](https://github.com/run-llama/llama_parse/assets/14369965/0ab6f46d-ae79-41a0-87c3-6d2f91118a82)

I receive a CORS error in the browser console :

`Access to fetch at 'https://api.cloud.llamaindex.ai/api/billing/checkout-session' from origin 'https://cloud.llamaindex.ai' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by irony** [comment]
We get the same error unfortunately when trying to upgrade our plan.

**Comment by irony** [comment]
Ping?

**Comment by zack-ashen** [comment]
I'm also getting this issue and would like to upgrade.

**Comment by BinaryBrain** [comment]
That's solved
