### ISSUE TITLE
Typo in LlamaParse Documentation

### ISSUE THREAD

**Issue by wiseant-co** [run-llama/llama_parse#164]
While going through the documentation found a typo in the API documentation's code example section. The API url mentioned is 'https://**docs**.cloud.llamaindex.ai/api/api_key' instead of 'https://**api**.cloud.llamaindex.ai/api/api_key'

You can have a quick view here https://docs.cloud.llamaindex.ai/llamaparse/API/get-keys-api-api-key-get

**Comment by logan-markewich** [comment]
this has been since fixed
