### ISSUE TITLE
table

### ISSUE THREAD

**Issue by Garvit4093** [run-llama/llama_parse#169]
parse tables in form of tables and not text

**Comment by guillaume-millot** [comment]
LlamaParse can output tables in json format:
https://github.com/dataforgoodfr/12_taxobservatory/blob/6f48852ae338f719d2a450cd417fdcd564ae0de1/country_by_country/table_extraction/llama_parse_extractor.py#L52-L69

**Comment by logan-markewich** [comment]
@guillaume-millot is right JSON (or even markdown) mode is what you'd want

https://github.com/run-llama/llama_parse/blob/main/examples/demo_json_parsing.ipynb
