### ISSUE TITLE
XLSX parsing not working

### ISSUE THREAD

**Issue by dereknissen** [run-llama/llama_parse#205]
I am currently trying to use the new XLSX parsing feature, but I am getting the following error:

Error while parsing the file './data/orgList.xlsx': Currently, only the following file types are supported: ['.pdf', '.doc', '.docx', '.docm', '.dot', ...] 

Is this an error on my end? I have pip re-installed LlamaParse and LlamaIndex already.

**Comment by hexapode** [comment]
Try to update your llama_pare package?

**Comment by dereknissen** [comment]
> Try to update your llama_pare package?

I did, but my kernel wasn't restarted. Fixed! Thanks.

**Comment by dereknissen** [comment]
Had to restart kernel
