### ISSUE TITLE
Usage count is wrong (GPT4-o)

### ISSUE THREAD

**Issue by johnjoubert** [run-llama/llama_parse#213]
I have a 14 page PDF and the usage count is showing as 140 when I use GPT4-o, but if I turn off GPT4-o, it reverts back to the correct count. Is this intentional?

<img width="382" alt="Screenshot 2024-06-05 at 11 03 29" src="https://github.com/run-llama/llama_parse/assets/16326211/7d7024eb-f4c2-4606-9b04-5c85e7c3bd63">

**Comment by logan-markewich** [comment]
It's intentional, although somewhat janky

Pricing is done per page. And gpt-4o costs more per page, so it's reflected here

Working on making this a little less jank
