### ISSUE TITLE
Use ChatGPT 4o from API call?

### ISSUE THREAD

**Issue by rickymerchant** [run-llama/llama_parse#214]
When previewing LlamaParse, I get the correct output when I select the GPT 4o mode, so I want to use that when calling the Llama_parse API, but it seems there are no options to use this mode when using the standalone API?

**Comment by maxqper** [comment]
Use `gpt4o_mode : true`.

 // sample javascript

```
    const formData = new FormData();
    formData.append('file', input.getValue().file);
    if (config.gpt4o_mode) {
      formData.append('gpt4o_mode', 'true');
    }
    const response = await fetch(`${baseUrl}/upload`, {
      method: 'POST',
      headers,
      body: formData
    });
```

**Comment by BinaryBrain** [comment]
We change the codebase for this feature. Please refer to the doc https://docs.cloud.llamaindex.ai/llamaparse/features/multimodal and repoen a ticket if you still encounter the issue.
