### ISSUE TITLE
Job not found

### ISSUE THREAD

**Issue by dpwidi** [run-llama/llama_parse#222]
response: Job not found, when using result analyze API

**Comment by nyckoo** [comment]
something's off, can't parse anything too

**Comment by sheresaidon** [comment]
Same - is there an outage?

**Comment by inrock1** [comment]
I can't parse any page all day using the Llamaindex client.

**Comment by andered** [comment]
Seems to be an outage....

**Comment by valentindjangone** [comment]
Still nothing. Eagerly waiting for that product to be reliable.

**Comment by andered** [comment]
You now need to choose the language:  If you don't select something (either on the web or API) it just hangs.

**Comment by garyblankenship** [comment]
I just get job not found for the job ids that are active in the llamaindex parser history.
