### ISSUE TITLE
CERTIFICATE ERROR

### ISSUE THREAD

**Issue by jaideep11061982** [run-llama/llama_parse#235]
SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED]

Error while parsing the file './uber_10q_march_2022.pdf': [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

I am getting this error while parsing if you can suggest the solution 
@seldo @hexapode @erichare @yisding @hatianzhang

**Comment by sujitsubhash7** [comment]
you need to add the certificate chain from openai to the certificates file in your conda environment
