### ISSUE TITLE
Error while parsing the file

### ISSUE THREAD

**Issue by sujitsubhash7** [run-llama/llama_parse#261]
I am getting an error message when I try to use LlamaParse.

from llama_parse import LlamaParse
documents = LlamaParse(api_key=api_key,result_type="markdown").load_data("../my_file.pdf")

the output I see is:

Started parsing the file under job_id xxx-xx.............
Error while parsing the file '../my_file.pdf': 'markdown'

**Comment by FlorentScarpaSustaain** [comment]
Seconded, especially since I did not have this issue yesterday running the exact same script that is failing today

Moreover, leaving `result_type` to its default value results in `Error while parsing the file '../my_file.pdf': 'text'`

**Comment by sujitsubhash7** [comment]
yeah, the output doesn't give much information about what is wrong. I even upgraded to the paid version but it still doesn't work. I had no issues with other smaller documents. This one is 2500 pages

**Comment by FlorentScarpaSustaain** [comment]
Mine is small, about 10 pages. I suspect a breaking change on the server side that conflicts with the client

**Comment by tanishq-ema** [comment]
Any explanations?

**Comment by FlorentScarpaSustaain** [comment]
Nothing so far, my guess is on a server-side error. I managed to get a result a couple times since the issue started, but most of the time it fails with a simple ERROR message (the error message evolved from the original one posted)

**Comment by raminos** [comment]
Same here most uploads fail.

**Comment by BinaryBrain** [comment]
This should be fixed since our latest API release.
If it happens again, please re-open this issue with the job ID and the new error message so we can have a look.
