### ISSUE TITLE
respect pageSeperator in LlamaParseReader

### ISSUE THREAD

**Issue by salehsed** [run-llama/llama_parse#263]
Would you please look into it the following code (TypeScript)
the results ignore the input and use "\n---\n" 

import {LlamaParseReader} from 'llamaindex'

`const parser = new LlamaParseReader(
        {
            resultType: 'text',
            pageSeperator: '\n---------MY_UNIQUE_SEPERATOR---------------\n',

            // doNotCache: true,
        }
    )`

**Comment by BinaryBrain** [comment]
Hi, thanks for reporting this bug.
We had a bug in our Typescript lib and I just opened the PR: https://github.com/run-llama/LlamaIndexTS/pull/1023
It should be working on our next release.
If you have any comment, please write them directly on the PR.
