### ISSUE TITLE
Unable to parse any pdf

### ISSUE THREAD

**Issue by SKashyap1999** [run-llama/llama_parse#266]
I am facing issues while using the LlamaParse python library. My usage is as follows:

p=LlamaParse(verbose=True, api_key="xxxxxxxx",parsing_instruction='''
                    Try your best to parse the table contents carefully and in a proper markdown format, without any formatting errors.''',
             language='en',gpt4o_mode=True,gpt4o_api_key=os.environ['OPENAI_API_KEY'],skip_diagonal_text=True)
    
json_objs=p.get_json_result(r"PATH_TO_PDF")

Error:
   Started parsing the file under job_id xxxxxxxxx
   Error while parsing the file PATH_TO_PDF: Failed to parse the file: xxxxxxxx, status: ERROR

What is the cause for this error? Is there a way to know what went wrong?

**Comment by FlorentScarpaSustaain** [comment]
I guess it's linked to how this issue started a couple days ago:

https://github.com/run-llama/llama_parse/issues/261

**Comment by BinaryBrain** [comment]
This should be fixed since our latest API release.
If it happens again, please re-open this issue.
