### ISSUE TITLE
The `target_page` parameter does not work correctly

### ISSUE THREAD

**Issue by KevinCaballeroCuriel** [run-llama/llama_parse#269]
I only need to parse the first page:

I tried like this:
```
document = LlamaParse(
    language="es",
    result_type="markdown",
    target_page="0,",
    parsing_instruction=parsing_instruction
).load_data("path")
```

And I also tried like this:
```
document = LlamaParse(
    language="es",
    result_type="markdown",
    target_page="0",
    parsing_instruction=parsing_instruction
).load_data("path")
```

But neither of both worked, it continued parsing all the pages and spending tokens for each page

**Comment by hexapode** [comment]
The correct syntaxe is target_pages (with a s)

This should work

```
document = LlamaParse(
    language="es",
    result_type="markdown",
    target_pages="0",
    parsing_instruction=parsing_instruction
).load_data("path")

```

Let me know if this fix the issue for you

**Comment by hexapode** [comment]
The doc is also updated, we were speaking about `target_page` instead of `target_pages`

https://docs.cloud.llamaindex.ai/llamaparse/features/parse_region
