### ISSUE TITLE
Error while parsing the file

### ISSUE THREAD

**Issue by Hicham-e** [run-llama/llama_parse#281]
i have been working with llamaparse for quite a while and never got this error until now. 
some documents get parsed without problems, and others get this error (Error while parsing the file 'file path' : 'markdown') even though i was working with the same documents before and never had problems with it. 
I even went llamaCloud and uploaded the documents there to test and still the same problem with the same documents i get this error (Result not found. Check job status to see if it has completed.)
here's one of those files if you want to test it:
[test.pdf](https://github.com/user-attachments/files/16180789/test.pdf)

**Comment by hexapode** [comment]
Thansk for repporting!

Seems to have been a cache issue, for some reason the initial job parsing failed, and the error result were cached.

I re-run the job with `invalidate_cache=true` and the result came back as expected on this document.

In a future release (next week) we will make sure to handle this corner case so it never happen again
