### ISSUE TITLE
Tracing using Langfuse

### ISSUE THREAD

**Issue by tkcoding** [run-llama/llama_parse#287]
Can we trace the page usage using Langfuse or any other framework ? 
**Purpose:**
To track page usage and view in dashboard.

**Comment by tkcoding** [comment]
@hexapode , is my understanding correct that currently to track the cost/pages used in llama-parse there's no API in place to pull that data?

**Comment by Disiok** [comment]
we have a usage API: https://docs.cloud.llamaindex.ai/API/usage-api-v-1-parsing-usage-get
also a parsing history API: https://docs.cloud.llamaindex.ai/API/get-parsing-history-result-api-v-1-parsing-history-get
