### ISSUE TITLE
Word-Level Modifications In High Entropy Documents if GPT-4o Enabled

### ISSUE THREAD

**Issue by adreichert** [run-llama/llama_parse#293]
# Summary

LlamaParse with GPT-4o enabled struggles to accurately reproduce random words. While probably not a common task, we've observed that feeding in longs lists random English words produces word-level modifications. Anyone hoping to use this tool to extract something like Base64 encoded data please be aware. There are 439 words in the original and 449 in the output. 136 words, or about 30%, were changed. Results are below. 

This seems tied to the LLM models.
* OCR mode didn't have any issues in our testing. It is advisable to try that mode first, especially if the document lacks formating. 
* I tried uploading a screenshot to Claude, and a similar problem occurred. (Actually, first it refused to do the parsing at all, and I had to tell the model that the image was a secret code that I needed to extract from a PDF.)
![image](https://github.com/user-attachments/assets/9533e143-dd89-4973-8ec0-5a2db1ec0297)

## Results
* PDF: [rw_page.pdf](https://github.com/user-attachments/files/16256589/rw_page.pdf)
* Diff: [diff_page.html.txt](https://github.com/user-attachments/files/16256593/diff_page.html.txt). You need to remove the `.txt` to view.

**Comment by hexapode** [comment]
Thanks for the report.

When using the multimodal mode, your document is transform into an 'image' per page that are then feed to a vendor mutli modal model for reconstruction (with gpt4o and Sonnet-3.5 supported for now).

This model are not yet as accurate as a traditional OCR for text extraction, however they show surprisingly strong performance on chart or complex document type. We provide them as a way to Parse as we expect them to improve greatly in the future.

**Comment by adreichert** [comment]
@hexapode Thank you for reviewing. Some of the errors seem to be attributable to the image conversion process. 
Small text is blurred and the kerning is off when compared with Mac's Preview. In one version of the random word test, three words `stagnum muscatoriums favoredly` got crushed  into `stagnumnusatoriorumfavoredly`, both in the image sent model and it's resulting text.

# Image
![image](https://github.com/user-attachments/assets/a5276e55-45c8-4c07-9ed8-826a52f7d6ae)
