### ISSUE TITLE
Automatic Chunking of PDF with LlamaParse

### ISSUE THREAD

**Issue by LeitlinienGPT** [run-llama/llama_parse#298]
My issue is that LlamaParse is automatically chunking my input PDF document.
Two weeks ago, I executed the same code and one big document was returned, which was not chunked.

I am using the SimpleDirectoryReader with LlamaParse (Version: 0.4.9)
Here is the code:

```py  
def get_meta(file_path):
    return {"source": file_path}

parser = LlamaParse(
      api_key=LLAMA_CLOUD_API_KEY,
      result_type="markdown" 
  )

  directory_path = "XXX"
  file_extractor = {".pdf": parser}
  reader = SimpleDirectoryReader( input_dir=directory_path,
                                  file_extractor=file_extractor,
                                  filename_as_id=True,
                                  file_metadata=get_meta
                                  )
  docs = reader.load_data()
```

Are those changes expected with updates in the last two weeks?

**Comment by adreichert** [comment]
This was added in 0.4.5, which was about three weeks ago. You can get the old behavior using the `split_by_page=False` to the `LlamaParse` constructor.  

Note I'm not with the LlamaParse team. The change caught me by surprise too.

**Comment by BinaryBrain** [comment]
Sorry for the breaking change. I think you found the solution @adreichert.
While we try to avoid breaking changes as much as we can, some can still appears.
I think the best way to avoid it is to freeze your package version.
