### ISSUE TITLE
Use of GPT 4o mini with Llama Parse

### ISSUE THREAD

**Issue by NG-201** [run-llama/llama_parse#303]
Do you plan to use gpt 4o for Llama Parse? I think it would solve the cost issues related to Llamaparse with GPT 4O and would allow much more capabilities with graphs and complex tables compared to the "classic" LlamaParse

**Comment by LLMR-boringtao** [comment]
On the cloud, we can use GPT 4O mini already. Still trying to find the API way to specify it though. Any help?

**Comment by LLMR-boringtao** [comment]
https://docs.cloud.llamaindex.ai/llamaparse/features/multimodal

**Comment by NG-201** [comment]
Thanks for adding the gpt 4o mini to Llama Parse. 
However, I was expecting the price to be lower: It is half the GPT 4O whereas the api cost is 25x less expensive. It is not the same order of magnitude.

**Comment by hexapode** [comment]
@NG-201 You can provide your own API Key. However the visual token of Gpt-4o-mini are really small compare to GPT-4, so you end up with a LOT of token per page to send the same image. They advertise cheaper token but they are not the same! On a sample of 10k page we were running at half the price per page of GPT-4o with GPT-4o mini, hence the pricing. Once we have seen an higher volume of pages we may update the price.
