### ISSUE TITLE
Cetain Excel file returns empty result in both Web UI and API

### ISSUE THREAD

**Issue by shawnli-capix** [run-llama/llama_parse#309]
**Describe the bug**
Some Excel files returns empty results in both Web UI and API. Other Excel files I tested do return expected results.

```
parser = LlamaParse(
            result_type=ResultType.MD, ignore_errors=False
        )
result = parser.get_json_result('path/to/Eqvista_DCF-Excel-Template.xlsx')
```
result:
```
[{'pages': [],
  'job_metadata': {'credits_used': 14.0,
   'credits_max': 1000,
   'job_credits_usage': 0,
   'job_pages': 0,
   'job_is_cache_hit': True},
  'job_id': 'cac11eca-ebec-4f09-b8ee-260c6a74aa9f',
  'file_path': 'path/to/Eqvista_DCF-Excel-Template.xlsx'}]
```

**Files**
The file showcasing the issue is actually the one in one of [LlamaParse Demo](https://github.com/run-llama/llama_parse/blob/main/examples/excel/dcf_rag.ipynb)
[Eqvista_DCF-Excel-Template.xlsx](https://github.com/user-attachments/files/16367657/Eqvista_DCF-Excel-Template.xlsx)

**Job ID**

cac11eca-917e-41a8-9fd0-01a0147d8e76

**Screenshots**
Feel free to also provide screenshots if relevant.

**Client:**
Both Frontend (cloud.llamaindex.ai) and Python Library has this issue in my test

**Options**
What options did you use? Multimodal, fast mode, parsing instructions, etc.
```
parser = LlamaParse(
            result_type=ResultType.MD, ignore_errors=False
        )
```

**Additional context**
Add any additional context about the problem here.

**Comment by hexapode** [comment]
Thanks for reporting, it should now work.

If the issue persist for cached job (job id start with `cac11eca`,  try to set `invalid_cache=True` in your query.
