### ISSUE TITLE
Result not found even the job status is 'SUCCESS'

### ISSUE THREAD

**Issue by benyamindr** [run-llama/llama_parse#318]
I got this error message:  {'detail': 'Result not found. Check job status to see if it has completed.'} <404> when tried to get the parsing result.
The job status is already 'SUCCESS'.

![image](https://github.com/user-attachments/assets/472ae3b0-b0c7-4212-a9ef-e9318c02f46f)

**Comment by hexapode** [comment]
We have a caching issue where cache was not restored correctly. Using invalidate_cache=True solve this issue.
Alternatively, everything should be back to normal in the next 5 minutes or so, but you will have to rerun your job.
