### ISSUE TITLE
Retrieval of completed job

### ISSUE THREAD

**Issue by shivam11** [run-llama/llama_parse#319]
I am having problem retrieving jobs with status = "SUCCESS".
I get the following error:
Error markdown file: 404 Client Error: Not Found for url: https://api.cloud.llamaindex.ai/api/v1/parsing/job/98d728c4-37bd-46d8-925d-ad909b375738/result/raw/markdown
and "98d728c4-37bd-46d8-925d-ad909b375738" is a valid job with status "SUCCESS"

**Comment by hexapode** [comment]
Hi!
We had a caching issue, using invalidate_cache=True would have solve this issue.
Everything should be back to normal in the next 5 minutes or so.
