### ISSUE TITLE
custom page break separator with new lines doesn't respect \n in frontend

### ISSUE THREAD

**Issue by PrathamSoni** [run-llama/llama_parse#322]
_Note: we're aware of some missing content in the output and layout issues on tables. Please refrain from opening new issues on this topic unless if you think it's different from what has already been reported._

**Describe the bug**
say i change the separator to `\n----\n` there will be literal `\n`'s in the output instead of new lines. only happens on frontend.

**Screenshots**
Feel free to also provide screenshots if relevant.

**Client:**
Please remove untested options:
 - Frontend (cloud.llamaindex.ai)

**Options**
standard options

**Comment by BinaryBrain** [comment]
Fix was fixed but we didn't close this issue.
