### ISSUE TITLE
target_pages parameter not affecting llama_parse behavior

### ISSUE THREAD

**Issue by dregules** [run-llama/llama_parse#325]
`def llama_parser():
    # from llama_index.core.schema import ImageDocument
    from llama_parse import LlamaParse
    os.environ["LLAMA_CLOUD_API_KEY"] = api_key
    instructions = "The provided document is an academic/scientific article. Some pages may contain figures, tables and/or formulas."
    parser = LlamaParse(
        # result_type="json",
        parsing_instructions=instructions,
        target_pages=[3,5,6], # also tried "3,5,6"
        language="en",
        verbose=True
        )
    return parser`

Returns all the pages no matter whether it's  `target_pages=[3,5,6]` or   `target_pages="3,5,6"` 
In the UI it seems to work fine and extract only as instructed per the target_pages. Python client not.

**Comment by BinaryBrain** [comment]
This is now fixed
