### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by shivam11** [run-llama/llama_parse#332]
Hi,
I am getting the follow 500 error when I am trying to upload a document for parsing:

500 Server Error: Internal Server Error for url: https://api.cloud.llamaindex.ai/api/parsing/upload
Is there any issue with the service?
Regards
Shivanand

**Comment by BinaryBrain** [comment]
Hi @shivam11,
It's possible we had a service issue at the same time. Can you please retry?
If it happens again, can you provide the file or JobID you're trying to process?
