### ISSUE TITLE
Not able to retrieve full extract of the parsed pdf

### ISSUE THREAD

**Issue by cardit1** [run-llama/llama_parse#335]
I have parsed multiple pdfs in different ways - web ui, post api, and python simplDir.. package.

1. But when retrieving there is no particular method to retrieve old jobs in python package.  
2. Different amounts of data are being retrieved in different methods ex - in api we are getting some 5000 words where as in python package only 2100 words are being retrieved, i have checked for any limitations variables in python but there are none 
 
Could any one please help me in this or if this looks like a bug please fix it

**Comment by BinaryBrain** [comment]
Hi @cardit1,
This discrepancy between the API and the python package shouldn't occur. Can you please provide your code and package version so that's we can debug it together?

**Comment by BinaryBrain** [comment]
Please reopen if you have more info.
