### ISSUE TITLE
Accessing active parsing jobs

### ISSUE THREAD

**Issue by AlexLMar** [run-llama/llama_parse#337]
![LlamaIndex report](https://github.com/user-attachments/assets/2252f7f0-0a2f-42a7-aafa-7d716511e950)

I'd like to access the result of the parsing job through the UI, but I don't seem to have any way of doing it. Am I missing something?

**Comment by BinaryBrain** [comment]
If the job is still "Active", you can retrieve the result using the API:
```
curl -X 'GET' \
  'https://api.cloud.llamaindex.ai/api/parsing/job/<job_id>/result/markdown' \
  -H 'accept: application/json' \
  -H "Authorization: Bearer $LLAMA_CLOUD_API_KEY"
```

If you cached your job, you can also simply resend the same document with the same parameters. Be careful, if there's a change in the parameters, the cache will not be used and it will use some credit to re-parse the file.
