### ISSUE TITLE
Can't run the BASIC of Basics

### ISSUE THREAD

**Issue by gordingin** [run-llama/llama_parse#338]
I pulled the report, and ran examples/demo_basic.ipynb

I pulled the PDF, added my key and then ran the cell with this inside

from llama_parse import LlamaParse

documents = LlamaParse(result_type="text").load_data("./attention.pdf")

I got this error

Error while parsing the file './attention.pdf': Failed to parse the file: Internal Server Error

**Comment by milest** [comment]
I'm seeing the same error for about 20 different pdfs.

**Comment by btyree** [comment]
Getting errors as well.

**Comment by btyree** [comment]
@BinaryBrain , things are all good on my end now.

**Comment by BinaryBrain** [comment]
Good to know! Feel free to ping us if you encounter more issues.
