### ISSUE TITLE
How can I use LlamaParse under FastAPI? (event loop error)

### ISSUE THREAD

**Issue by cay89** [run-llama/llama_parse#344]
When I try to parse my .pdf file in my FastAPI application using the following code:

```python
file_path = self._download_file_if_not_exists()

# set up parser
parser = LlamaParse(
    api_key=self.config.llama_cloud_api_key,
    result_type=ResultType.JSON,
    language=Language.HUNGARIAN,
    show_progress=True,
)

# use SimpleDirectoryReader to parse our file
file_extractor = {".pdf": parser}
documents = SimpleDirectoryReader(
    input_files=[file_path], file_extractor=file_extractor
).load_data(show_progress=True)

print(documents)
```

I've got the following error:

> Failed to load file docs/1k4WEyYIjSaN4tqmG8Ytt3BLdeqa6IaJK.pdf with error: The event loop is already running. Add `import nest_asyncio; nest_asyncio.apply()` to your code to fix this issue.. Skipping...
/python3.12/site-packages/llama_index/core/readers/file/base.py:553: RuntimeWarning: coroutine 'LlamaParse.aload_data' was never awaited
  return []
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

I then tried adding the `nest_asyncio.apply()` workaround, but it didn't work:

> ValueError: Can't patch loop of type <class 'uvloop.Loop'>

So, what should i do?

**Comment by cay89** [comment]
The `nest_asyncio.apply()` fix only works if I start my app with "asyncio" loop:

```bash
uvicorn src.main:app --reload --loop "asyncio"
```

**Comment by cay89** [comment]
It works, although the ideal solution is probably to call LlamaParse from some background process, not directly from FastAPI.

**Comment by awandzel** [comment]
Thanks, @cay89 -- GJ with the work around.
