### ISSUE TITLE
Parse .pdf that contains images what build from small pieace of images

### ISSUE THREAD

**Issue by cay89** [run-llama/llama_parse#347]
What solution exists if the processed file has images made up of smaller images, but I need the entire image as it appears in the document? For example, here is this user manual: https://partners.gorenje.com/fts/GetDigitDoc.aspx?sifra=588561&jezik=en&tipVsebine=1&docName=gv61010uk_en.pdf

Now, if I process this with LlamaParse and download the images, I get something like this:

![image](https://github.com/user-attachments/assets/9013d356-bef9-4ead-8825-63490942c33b)

Is there a solution for this?

**Comment by BinaryBrain** [comment]
Hi @cay89,
I don't know any tool that handles re-stitching tiles together.
Thus said, if you use the Json output, you have the dimensions and coordinates of every images so you can create a script that detect if two images are side by side and merge them together.

I'm sorry but this is currently not in the scope of LlamaParse, so I'll close it as "won't fix".
I you have an important use case with it, please tell us.

**Comment by cay89** [comment]
@BinaryBrain It's fine, I was just wondering if there was an easier solution than piecing it together myself. But since I won't be dealing with this type of PDF files for the time being, thanks for the answer!
