### ISSUE TITLE
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:

### ISSUE THREAD

**Issue by gaussiangit** [run-llama/llama_parse#348]
I am behind corporate proxy and I get following error. 
SSLError: HTTPSConnectionPool(host='api.cloud.llamaindex.ai', port=443): Max retries exceeded with url: /api/parsing/upload (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)')))

**Comment by BinaryBrain** [comment]
Have you asked you corporate security team about this?
They probably put a web proxy to do MitM so the certificate validation fails because their corporate certificate defers from our official certificate.
