### ISSUE TITLE
Extracting tables and text information separately using parser

### ISSUE THREAD

**Issue by sarathsurpur** [run-llama/llama_parse#35]
Hi Team,

We have already created rag pipeline using Unstructured io package as pdf parser, with this we can extract the table and text separately based on the extracted information, I have an approach to summarise the tables and text to save in vector db, I would like to continue using the same pipeline with this parser, unfortunately I don't see any option to extract the table data alone to continue using my pipeline. Could you please let me know will there be any option like this in future

**Comment by hexapode** [comment]
We are working on a JSON output that will allow you to filter table easily.

**Comment by hexapode** [comment]
We have released `Json` output which give you the table in different format: Md, txt, csv and json.
