### ISSUE TITLE
Documents do not finish processing or fail/time out. 

### ISSUE THREAD

**Issue by ianpcook** [run-llama/llama_parse#352]
_Note: we're aware of some missing content in the output and layout issues on tables. Please refrain from opening new issues on this topic unless if you think it's different from what has already been reported._

**Describe the bug**
We submit documents for text and information extraction to the `standard` version of Llamaparse. We have run across a couple documents that, after being submitted, never stop processing, and do not either fail or time out. 

[Airbnb 2023 10k Forever.pdf](https://github.com/user-attachments/files/16618573/Airbnb.2023.10k.Forever.pdf)

**Job ID**
If you have it, please provide the ID of the job you ran.
You can find it here: https://cloud.llamaindex.ai/parse in the "History" tab.

**Screenshots**
Feel free to also provide screenshots if relevant.

**Client:**
Python Library

**Options**
Code: 
`self.client = LlamaParse(
            api_key=LLAMA_CLOUD_API_KEY,
            result_type=ResultType.TXT, 
        )`

**Additional context**
Add any additional context about the problem here.
[Text forever.txt](https://github.com/user-attachments/files/16618574/Text.forever.txt)

**Comment by BinaryBrain** [comment]
Hi @ianpcook,
I couldn't reproduce the issue. Do you still have the JobID and maybe your Python code?

**Comment by ianpcook** [comment]
Looks like we're no longer running into the issue, though we did all that day. Here's a JobID from that work: 

302a2ee7-d765-421d-a4a6-154040b6e4aa
