### ISSUE TITLE
Document Too large, max page is undefined

### ISSUE THREAD

**Issue by sebakthapa** [run-llama/llama_parse#359]
# Error
```json
{
    "id": "da677385-843c-44d7-8a00-cbcd52cd3d01",
    "status": "ERROR",
    "error_code": "DOCUMENT_TOO_LARGE",
    "error_message": "Document too large, max pages is :undefined."
}
```

Got the above error when hitting `/api/parsing/upload` with `gpt4o_mode=true`.

## About the Document
size: 6.95MB
type: pdf
page_count: 232

Sending parse request without `gpt4o_mode` param is working fine.

**Comment by BinaryBrain** [comment]
Nice catch! I'm on it.

**Comment by BinaryBrain** [comment]
This has been fixed in the code and will reflect in the next release. Limit is still 200 for multimodal.
