### ISSUE TITLE
Error while parsing the file 'filename.pdf': 'json'

### ISSUE THREAD

**Issue by johnisanerd** [run-llama/llama_parse#383]
I get the following output when I run this code:

```
documents = LlamaParse(

        result_type="json",
        split_by_page=False,
        parsing_instruction=extraction_instructions
    ).load_data(pdf_path)  
```
Gives the error:

```
Started parsing the file under job_id 6e516bf7-de76-4f0a-85be-da416364a5ca
Error while parsing the file '18f0aecc51523b1b_attachment_2.pdf': 'json'
```
This returns:  
`[]`

Verbose does not seem to expand the error message.

Changing the result_type to markdown does not throw an error.

**Client:**
 - Python Library

**Comment by BinaryBrain** [comment]
Hi @johnisanerd,
It's a bug. You're job was already cached, the cache was restored but you should see the retrieved json.

**Comment by johnisanerd** [comment]
Should I be able to re-run this code now and see json coming out?

**Comment by katzurik** [comment]
Had the same issue, can't manage to use the API with json type. Any workaround?

**Comment by BinaryBrain** [comment]
@katzurik The API is working on my side. Can you provide your code?

**Comment by katzurik** [comment]
> @katzurik The API is working on my side. Can you provide your code?

import json
from llama_parse import LlamaParse
import os

api_key= ''



parser = LlamaParse(
    api_key=api_key,  
    result_type="json",
    num_workers=4, 
    verbose=True,
    language="en",  
)

documents = parser.load_data(file_path)

Output:
Started parsing the file under job_id ..some job_id ... 
Error while parsing the file 'some file.pdf': 'json'

**Comment by BinaryBrain** [comment]
Hmm, I agree we have an issue with types in the lib. Will patch it.
For JSON output, you're supposed to use:
```py
json_objs = parser.get_json_result(file_path)
json_list = json_objs[0]["pages"]
```

See this example: https://github.com/run-llama/llama_parse/blob/main/examples/demo_json.ipynb

**Comment by AndreaLRM** [comment]
Hi, I had the same issue. No idea how to get the retrieved json file. Also, the link for the demo_json notebook you provided is broken.

**Comment by BinaryBrain** [comment]
Hi @AndreaLRM,
We now have a new way of getting data that's should be more user-friendly: https://github.com/run-llama/llama_cloud_services/blob/main/examples/parse/demo_json_tour.ipynb
