### ISSUE TITLE
Version solving failed on windows

### ISSUE THREAD

**Issue by AdrienLF** [run-llama/llama_parse#385]
Describe the bug
There's a dependency conflict when trying to install the project dependencies using Poetry. The issue appears to be between llama-index (0.11.6) and llama-index-vector-stores-postgres (^0.1.1), which have incompatible requirements for llama-index-core.
Files
N/A (This issue is not related to a specific PDF file)
Job ID
N/A (This issue is not related to a parsing job)
Screenshots
N/A (No screenshots provided, but the terminal output is sufficient)

Client:
Python Library

Options
N/A (This issue is related to project setup, not parsing options)

Additional context
I encountered this issue while trying to set up a new project using npx create-llama@latest. The project was created successfully, but when trying to install dependencies using Poetry, the following error occurs:
```
Because no versions of llama-index-vector-stores-postgres match >0.1.1,<0.1.2 || >0.1.2,<0.1.3 || >0.1.3,<0.1.4.post1 || >0.1.4.post1,<0.1.5 || >0.1.5,<0.1.6 || >0.1.6,<0.1.7 || >0.1.7,<0.1.9 || >0.1.9,<0.1.10 || >0.1.10,<0.1.11 || >0.1.11,<0.1.12 || >0.1.12,<0.1.13 || >0.1.13,<0.1.14 || >0.1.14,<0.2.0
 and llama-index-vector-stores-postgres (0.1.1) depends on llama-index-core (>=0.10.1,<0.11.0), llama-index-vector-stores-postgres (>=0.1.1,<0.1.2 || >0.1.2,<0.1.3 || >0.1.3,<0.1.4.post1 || >0.1.4.post1,<0.1.5 || >0.1.5,<0.1.6 || >0.1.6,<0.1.7 || >0.1.7,<0.1.9 || >0.1.9,<0.1.10 || >0.1.10,<0.1.11 || >0.1.11,<0.1.12 || >0.1.12,<0.1.13 || >0.1.13,<0.1.14 || >0.1.14,<0.2.0) requires llama-index-core (>=0.10.1,<0.11.0).
...
And because llama-index-vector-stores-postgres (0.1.14) depends on llama-index-core (>=0.10.20,<0.11.0)
 and llama-index (0.11.6) depends on llama-index-core (>=0.11.6,<0.12.0), llama-index (0.11.6) is incompatible with llama-index-vector-stores-postgres (>=0.1.1,<0.2.0).
So, because app depends on both llama-index (0.11.6) and llama-index-vector-stores-postgres (^0.1.1), version solving failed.
```

I've tried the following steps to resolve the issue:

Using Python 3.11 (as specified in the project requirements). Python 3.12 fails also.
Removing the `poetry.lock` file and trying to install dependencies again
Updating Poetry to the latest version

None of these steps resolved the dependency conflict. It seems that the create-llama template might be specifying incompatible versions of these packages.

**Comment by logan-markewich** [comment]
@AdrienLF you'll need to update `llama-index-vector-stores-postgres`  - v0.2.2 is out
