### ISSUE TITLE
Issue with Parsing and No Error/Timeout

### ISSUE THREAD

**Issue by m9e** [run-llama/llama_parse#39]
Using fedex 10-K from https://d18rn0p25nwr6d.cloudfront.net/CIK-0001048911/a9687faf-0a00-4135-a02e-0fc07e15d117.pdf

![Screenshot 2024-02-27 at 9 06 47 AM](https://github.com/run-llama/llama_parse/assets/916184/1fb8f142-c3a2-4e80-9137-3eedc56553a4)

Received an error using the example code roughly, with no actual error output.

I suspect the issue here is that the client has a timeout not in the example code, because I uploaded the PDF to the llamaparse UI, it parsed successfully (at least, on the surface it did) - and then I noticed it was showing 446/1000 - the PDF is 223 pages long. So I'd conclude it worked, the client thought there was an error because it gave up too soon (it seemed like about 8-9 minutes when I did the ui drag and drop), which made me unable to access the output, but each attempt (ui+notebook) used the pages.

**Comment by httplups** [comment]
Same here. It started happening when I used docker container :(

**Comment by BinaryBrain** [comment]
I just tried to reproduce but couldn't. It probably has been fixed in a past release.

Please reopen this issue if you still encounter it.
