### ISSUE TITLE
LlamaParse not Processing PDFs (2024-09-09)

### ISSUE THREAD

**Issue by adreichert** [run-llama/llama_parse#391]
**Describe the bug**
We are unable to process PDFs. I filed a job with the UI, which failed. The issue seemed to start about 2.5 hours ago.

**Job ID**
73dc7fff-536f-4b3f-89cb-2c6dd538cdd8
8f4c3149-d7fc-4168-8500-66dcf3286b10

**Options**

Vendor Multimodal. "Accurate" mode parsing seems to be working.

**Comment by hexapode** [comment]
Just push an hotfix, your document should now parse correctly, let me know if it still fail.

**Comment by adreichert** [comment]
Processing has resumed on my side.
