### ISSUE TITLE
Not extracting full text from pdf

### ISSUE THREAD

**Issue by imukulmunjal** [run-llama/llama_parse#393]
Not extracting complete text from pdf 

Job Id - 316cf20b-9463-46c6-8d69-b393fef2d6ed

**Comment by hexapode** [comment]
Hi!
Thanks for flagging.
One of the font use in this PDF made our parser bug. We have build a fix and are currently evaluating on staging. Will let you know when it is ready to test again.

**Comment by hexapode** [comment]
You should now be able to parse this document successfully. If you re-run the job, please run it with `invalidate_cache=True` so you do not retrieve the previously non parsed correctly version of your document.

**Comment by imukulmunjal** [comment]
works now, thanks
