### ISSUE TITLE
Issue with sending the Webhook

### ISSUE THREAD

**Issue by wus-solutions** [run-llama/llama_parse#396]
If I parse a document in the sandbox and specify a webhook, the document is parsed, but the webhook is not executed. No credits are calculated either, although the Markdown is displayed in full in the sandbox (JobId: 5a04a678-630d-47ad-84f8-3a373fd830c0). If I use the same document in the sandbox but without the webhook, I am charged the credits (JobId: 5371c0d1-63c3-4d58-8e31-62fa8306169f). There seems to be a problem with this PDF, as my normal workflow via API works with other PDFs. Unfortunately I can't see what the problem is.

**Comment by BinaryBrain** [comment]
Hi @wus-solutions,
On your first job (5a04a678-630d-47ad-84f8-3a373fd830c0) you had a "Cache Hit", in which case we simply return the cached result (free of charge) and the webhook isn't called.
That said, we can consider the webhook not being called as a bug and we'll add it on the cached results as well.

**Comment by hexapode** [comment]
This now should work as expected in production. thanks for reporting the bug.
