### ISSUE TITLE
Return positional information

### ISSUE THREAD

**Issue by eburnette** [run-llama/llama_parse#40]
I'd like to parse the document and get positional coordinates for each section of text and each table cell. This would take the form of a page number and a (x1,y1,x2,y2) rectangle. If the text spans a page, you might need to provide multiple coordinates. If the document doesn't have pages, then some other coordinate system appropriate to the document type should be used such as characters or lines.

**Comment by hexapode** [comment]
We will not offer this feature. A lot of system do OCR / character extraction (look at tika for PDF, ...) very well, and our goal is to have the best parser to prepare data for RAG.

The nearest to what you describe is our current text output (you could consider the x,y as the column row in the text.
