### ISSUE TITLE
LlamaParse returns more pages than original document

### ISSUE THREAD

**Issue by galvangoh** [run-llama/llama_parse#404]
**Describe the bug**
Using the python version of LlamaParse. The original document has 8 pages, after parsing there are 13 pages worth of results. Document footer and some regions of a page were being recognized as a page by itself (some regions only have a single line of text).

**Job ID**
a857fc5a-183a-41ff-befd-ce6f366344a6

**Options**
Multimodal model: gpt-4o
parsing instructions:
```
You are an intelligent document parser. The provided document is an invoice
containing details like invoice number, date, customer, supplier, delivery,
payment, and total. It also includes a table of products or services, sometimes
with sub-components. Your task is to accurately parse all text and tables,
taking into careful consideration the contents and structure of the invoice.

 The table's content may vary:
- Item content can span multiple lines, often in the description column or
others.
- Some columns may be empty or partially filled.
- Item information may be interspersed within a column.
- Table headers and their data may be multi-tiered.

The invoice can be of the following variant based on the table content:
- Service: Descriptions mention services (e.g. rental, maintenance,
consultation, or repair).
- Product: Descriptions include items like tools, equipment, or machinery with
columns for item codes, quantity price, etc.
```

**Comment by BinaryBrain** [comment]
Hi @galvangoh,
GPT 4o likes to add this kind of separators and it can conflict with our page separators.
The best way to make sure you get the correct page split is to fetch the Json output instead of the Markdown one.
The other "hacky" solution is to specify your own page separator (i.e. `\n______\n`) and hope 4o won't do the same. This usually works but isn't guaranteed.

**Comment by galvangoh** [comment]
HI @BinaryBrain,
I will try using custom page separator. As im parsing document via azure blob reader, it currently does not support JSON output.
