### ISSUE TITLE
Webhook JSON is wrong

### ISSUE THREAD

**Issue by wus-solutions** [run-llama/llama_parse#408]
Hi, 
your JSON Response on the webhook should look like this in the Sandbox:
{
  "txt": "raw text",
  "md": "markdown text",
  "jsonOutput": [{
    "page": 1,
    "text": "page 1 raw text",
    "md": "page 1 markdown text",
    "images": [{ "name": "img_p0_1.png", "height": 100, "width": 100, "x": 0, "y": 0 }] }],
  "images": [ "img_p0_1.png" ]
}

if i recieve an Webhook from LLamaParse the "jsonOutput" is now "json"
is that correct?

**Comment by BinaryBrain** [comment]
@wus-solutions Thanks for reporting. The documentation is wrong, the key is and will always be `json`.
I'm pushing the fix now.
