### ISSUE TITLE
Good working script processing api, now returns "markdown": "NO_CONTENT_HERE"

### ISSUE THREAD

**Issue by weisisheng** [run-llama/llama_parse#419]
**Describe the bug**
Using AWS lambda / axios with a function that has been in dev for the last few months.  Tried running otday, ingesting multiple example pdfs, and the error returns "NO CONTENT HERE"

**Files**
https://hiring-report-public-files.s3.amazonaws.com/CSR_BioRender.pdf

It's called "misc-text.pdf" on the llamaparse console since I am sending it to /tmp file first from S3 before hitting the endpoint.

**Job ID**
If you have it, please provide the ID of the job you ran.
1eb1b8e0-b354-430c-bad6-3568fea0bc85

**Screenshots**
# results from aws step functions / lamba
https://hiring-report-public-files.s3.amazonaws.com/Screenshot+from+2024-09-29+10-40-08.png

**Options**
Fast, no other instructions.

**Additional context**
Add any additional context about the problem here.

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme

you may need to install the c compiler

**Comment by weisisheng** [comment]
Nah I am sure i don't.   Stop with the phishing attacks, punk.

Noticed there is an error referencing the url in this documentation (two backslashes):

"https://api.cloud.llamaindex.ai//api/v1/parsing/upload"

 Found here: https://docs.cloud.llamaindex.ai/API/upload-file-api-v-1-parsing-upload-post

**Comment by weisisheng** [comment]
Closing this for now, seems the files are being corrupted further upstream during s3 posting process.
