### ISSUE TITLE
would be nice to remove header\footer from pdf 

### ISSUE THREAD

**Issue by cognitivetech** [run-llama/llama_parse#42]
probably a tricky ask, but when working with academic texts especially, but really books or any pdf will commonly have header footer information.. just gets in the way. especially using for rag, that can alter the understanding of a chunk.

I know it slows me down in manual review.. 

![image](https://github.com/run-llama/llama_parse/assets/55156785/98b6363b-4252-4bef-a494-4bbb6ab88c75)

**Comment by Disiok** [comment]
Thanks for raising this. It's on the roadmap to improve!

**Comment by hexapode** [comment]
You now have 2 way to remove header footer.
- Using a parsing instruction like `"Remove headers and footers`
- Using a bounding box to select the area of the page you want to parse (can be set to ignore footer and headers)

**Comment by sridhardkamoji** [comment]
You can use this approach to remove the header and footer notes. We have implemented a similar version in our organization, and it seems to work pretty well. This uses pymupdf (fitz) package
[link](https://github.com/pymupdf/PyMuPDF/discussions/2259)
