### ISSUE TITLE
Llamparse within SimpledirectoryReader doesn't accept PurePosixPath

### ISSUE THREAD

**Issue by seeifsalem** [run-llama/llama_parse#421]
**Describe the bug**
I am using LlamaParse as an extractor within a SimpleDirectoryReader with fs as an s3 bucket. What will happen is that when load_data() from LlamaParse is called, the file_path will be a PurePosixPath (because of the design of SimpleDirectoryReader). 
`_Path = Path if is_default_fs(self.fs) else PurePosixPath`

The problem is that in llama_parse\base.py line 367 we have this check     
        [`if isinstance(file_path, (str, Path, bytes, BufferedIOBase)):`](https://github.com/run-llama/llama_parse/blob/2ccd2a9397ca478a3539e41fb274ffd37f03f45b/llama_parse/base.py#L367)
It doesn't include PurePosixPath as an accepted instance so we can't load our files.

This should be an easy fix:
`        if isinstance(file_path, (str, Path, PurePosixPath, bytes, BufferedIOBase)):
`

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
