### ISSUE TITLE
premium mode code example

### ISSUE THREAD

**Issue by zahidekilic** [run-llama/llama_parse#425]
When I parse the same document from the web interface with llamaparse premium, it reads it very well, but when I do it via the API, it reads it in lower quality. Can you share the python code of the premium parse operation done with the default options, without any options selected from the web interface?

**Comment by BinaryBrain** [comment]
Hi @zahidekilic,
Premium Mode is working on my side when using the `premium_mode` parameter set to `true` via the API.
Can you give me the JobID you have when calling the API?
Maybe also the part of the code where you call the API.

**Comment by zahidekilic** [comment]
updating llama-index package saved my day. thank you for your response.

**Comment by BinaryBrain** [comment]
You're welcome :)
