### ISSUE TITLE
Parsing Instructions passed not getting executed

### ISSUE THREAD

**Issue by qasim-mobi** [run-llama/llama_parse#427]
**Describe the bug**
The Parsing Instructions passed using the default 'Accurate' mode is not getting executed on the extracted data

**Job ID**
e50484e6-69d2-4373-8456-2053984c383e

**Options**
Default Accurate mode, parsing instructions, Donot Unroll column.

**Comment by rnyffeler** [comment]
Same thing happened to me.

**Job ID**
26d47424-2e23-4be6-845d-e5ad5673fef7

**Options**
Default accurate mode; parsing instructions

**Comment by bjmvercelli** [comment]
Same thing here. 

Tested with Fast, Accurate and Premium mode. Only premium mode is executing parsing instructions

**JOBS IDS**
- Premium: c093b218-5bac-4814-8d86-a0bb460a456c	
- Accurate: abca3da0-5cd8-4b52-8214-78795f8d272e	
- Fast: 6f5c15a1-16ab-46be-a73e-793236e30ae9

**Comment by BinaryBrain** [comment]
Hi everyone,
We had a bug on our parsing instruction and by fixing it, it broke your pipelines.
We just released a feature flag `is_formatting_instruction` that is `True` by default to reproduce the old behavior.
That mean you should be able to use the parsing instruction as you used to.

If you wish to use our formatting prompt, you can still pass a parsing instruction and set the `is_formatting_instruction` flag to `False`.
