### ISSUE TITLE
Issue with LlamaParse chokes if I try to specifically access page 0 (the cover) of a pdf

### ISSUE THREAD

**Issue by kpkpkp** [run-llama/llama_parse#428]
Page Specification | Target Pages 
![Screenshot 2024-10-03 184946](https://github.com/user-attachments/assets/99630c35-5814-49c8-95dc-45b6e7199895)

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by BinaryBrain** [comment]
Hi @kpkpkp,
This is now fixed. Thanks for reporting it.
