### ISSUE TITLE
Issue with LlamaParse ...i have a pdf document that is a mix of structured, searchable pages combined with scanned pages.  When parsed via llamaparse, I only receive the structured pages as output

### ISSUE THREAD

**Issue by TegoSys** [run-llama/llama_parse#432]
b07df486-2f8b-4dd7-80a7-67ef3f397345

i used advanced mode, with and without parsing instructions.  With instructions, I explained the document is a mix of searchable and unsearchable pages.

**Comment by TegoSys** [comment]
sorry, meant to say "accurate" mode

**Comment by BinaryBrain** [comment]
Hi @TegoSys, would it be possible to share your document with us?

Also, we fix some issues on the parsing instruction for accurate mode. Could you retry to see if it works better now, and send us the jobID of the rerun?

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
