### ISSUE TITLE
Unable to parse Excel sheets

### ISSUE THREAD

**Issue by chaimajaballah0** [run-llama/llama_parse#440]
I am unable to parse an excel file that have multiple sheets. It always comes as unsupported type error. 
How to solve this?
I tested the notebook example with the same provided excel file, LlamaParse works fine. However, even the structure of my excel files looks the same as the example, LlamaParse prints this error on the colab notebook and in local script.

![Screenshot 2024-10-14 at 3 24 40 PM](https://github.com/user-attachments/assets/24634bdc-c3d7-4fdc-bad8-36efa1d5a4ae)

**Comment by BinaryBrain** [comment]
Hi @chaimajaballah0,
Due to some issue with Excel files, we had a file size limit of 2Mb.
We've just increased it to 130Mb.
Can you retry to run your job and also send me the jobID if it fails again?

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by chaimajaballah0** [comment]
Hello, 
the job ran successfully. 
Thank you for solving the issue.
