### ISSUE TITLE
When llama-parse converts table-like sections to tables, the `bBox` property seems to use a default value which is not useful

### ISSUE THREAD

**Issue by dan-cooke** [run-llama/llama_parse#442]
**Describe the bug**
This is a pretty niche one. 

but when llama-parse identifies a "table-like" section in a document
![image](https://github.com/user-attachments/assets/be7b3269-cdb3-4e2c-836b-9eaf8b61443a)
In this example the section that starts:
```
Adviser fee: 0.50%
Platform fee: 0.30%
Underlying Fund costs: 0.22%
```

Is parsed as a table in the output:
```.json
  {
        "type": "table",
        "rows": [
          [
            "Fee Type",
            "Percentage"
          ],
          [
            "Adviser fee",
            "0.50%"
          ],
          [
            "Platform fee",
            "0.30%"
          ],
          [
            "Underlying Fund costs",
            "0.35%"
          ],
          [
            "Sarasin Discretionary Management Charge",
            "0.60%"
          ],
          [
            "Total Ongoing charges",
            "1.75%"
          ]
        ],
```

This is actually a great feature, i really like this. 

## The problem
When this parsing happens, it appears that the `bBox` property is no longer useful:
```.json
        "bBox": {
          "x": 0,
          "y": 0,
          "w": 595.3,
          "h": 841.89
        }
```

## Workaround
I can pass a parsing instruction to say something like "Do not interpret table like structures as tables" but as I said... I actually really like this feature, so I'd rather not do that. Its much cleaner for our users to see a MD table instead of raw text for sections like this

**Files**
[templi_J Bloggs & J Doe Illustration for New investments.docx](https://github.com/user-attachments/files/17367120/templi_J.Bloggs.J.Doe.Illustration.for.New.investments.docx)

**Job ID**
1e0fa80c-b97f-4107-b720-ee6dd62845b8
You can find it here: https://cloud.llamaindex.ai/parse in the "History" tab.

**Screenshots**
### Trying to draw a bounding box on my ui with this bug
![image](https://github.com/user-attachments/assets/c42e461b-9e13-4227-a66e-43e5b9f629ae)
As you can see one of the bounding boxes is (nearly correct) I believe the height is slightly wrong, but that is already raised #368, but the table parse is causing a box to be drawn around the entire document which is not quite right

 
**Client:**
 - Python Library

**Comment by hexapode** [comment]
Great feedback thanks, this is actually a new feature will improve in coming weeks!

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by BinaryBrain** [comment]
This has finally been fixed!
