### ISSUE TITLE
Parsing does not work with files with no extensions (but a correct MIME type)

### ISSUE THREAD

**Issue by LouisLecouturier** [run-llama/llama_parse#452]
Hi all !

I have a use case where I download files from an S3 bucket (pdf, word, powerpoint files, without extensions) and want to parse them.

Files have correct mime types but just do not have any extension.
So when I try to load them using Llama Parse, I get errors.

Is there a way to tell Llama Parse to "infer the extension" from the MIME type ?

Thanks !

**Comment by BinaryBrain** [comment]
Hi @LouisLecouturier,
How are you uploading your documents to LlamaParse? Using the Python lib? the API? frontend?

LlamaParse is usually able to guess the extension but it may not work on uncommon types of documents.

Can you also send me your jobID so I can see what's going on?

**Comment by BinaryBrain** [comment]
Cool!
Yes, it's better to have the extensions. We're trying to guess the MIME type when there's no extension provided but it's not 100% reliable (especially when files are corrupted). It's more a user-friendly thing than a stable feature.

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
