### ISSUE TITLE
Failed to load the Excel document

### ISSUE THREAD

**Issue by Rainismer** [run-llama/llama_parse#456]
from llama_parse import LlamaParse

parser = LlamaParse(
        api_key="..."
    )
docs = parser.load_data("D:\\111.xlsx")

why docs is []?

**Comment by BinaryBrain** [comment]
Hi @Rainismer,
We're currently limiting .xlsx files to 2Mb: https://docs.cloud.llamaindex.ai/llamaparse/limits
That said, the limit will be increased in a few days.

Can you check the size of your file?

**Comment by Rainismer** [comment]
@BinaryBrain When will the limit be increased? To what amount?

**Comment by hexapode** [comment]
The limit have been increase to 130Mb

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
