### ISSUE TITLE
UI: "This is an early preview..." banner overflows horizontally on the trailing edge of the window

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [run-llama/llama_parse#46]
Just a minor UI bug (does not seem to impact functionality)

![Screenshot 2024-02-28 at 12 54 03 PM](https://github.com/run-llama/llama_parse/assets/5123191/b9f3d311-7303-4126-abfe-a08a5c5ffe10)

**Comment by Disiok** [comment]
Thanks for raising the issue!
