### ISSUE TITLE
Extremely slow processing and timeouts

### ISSUE THREAD

**Issue by dan-cooke** [run-llama/llama_parse#466]
**Describe the bug**
I'm just reopening a bug for slow processing, we have noticed incredibly slow processing times over the last week, we have received a few complaints from customers about this.

Investigating the issue has led us to Llama Parse being the cause. 

On multiple occasions uploading a simple 3 page PDF even via the Parse UI takes well over 5 minutes. 

It seems to happen sporadically, a lot of the time its super fast. 

This is actually why we stopped using Textract and switched to Llama Parse, but right now its worse than Textract again so we are considering moving back

Apologies that I can't provide more information - as I say its entirely sporadic, and happens in the Python sdk and the Parse UI itself

## Update:

Just received an error from the API

Job ID: 10e49a48-2872-48f7-8ed1-f8614aab72dd failed with status: ERROR, Error code: ERROR_DURING_PROCESSING, Error message: An unknown error occurred during processing. Job id: 10e49a48-2872-48f7-8ed1-f8614aab72dd

I can only assume there is an incident? CAn't see anything reported however

**Comment by hexapode** [comment]
Could you retry, we experienced a high number of error on the cluster in past hours, but now it should be normal again.

**Comment by darrenangle** [comment]
+1

**Comment by dan-cooke** [comment]
> Could you retry, we experienced a high number of error on the cluster in past hours, but now it should be normal again.

Yes thank you for the prompt resolution, it has been quite stable for the past day or 2
