### ISSUE TITLE
Unknow Error Occured while parsing It is coming for all the PDF  - e9749617-ea3d-4946-8a63-20a83b2fbc85

### ISSUE THREAD

**Issue by kabashik786** [run-llama/llama_parse#467]
**Describe the bug**
Write a concise description of what the bug is.

**Files**
If possible, please provide the PDF file causing the issue.

**Job ID**
If you have it, please provide the ID of the job you ran.
You can find it here: https://cloud.llamaindex.ai/parse in the "History" tab.

**Client:**
Please remove untested options:
 - Python Library
 - API
 - Frontend (cloud.llamaindex.ai)
 - Typescript Library
 - Notebook

**Additional context**
Add any additional context about the problem here.
What options did you use? Premium mode, multimodal, fast mode, parsing instructions, etc.
Screenshots, code snippets, etc.

**Comment by hexapode** [comment]
Could you retry, we experienced a high number of error on the cluster in past hours, but now it should be normal again.

**Comment by kabashik786** [comment]
Thanks it is working fine. Do we have any alerts onto this. As we are planning for production.

**Comment by BinaryBrain** [comment]
Hi @kabashik786,
This is our status page: https://llamaindex.statuspage.io
If it's not sufficient for you to go in production, please reach out and let's figure out a fitting solution for you.
