### ISSUE TITLE
Error parsing markdown (Parse -> Try demo)

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [run-llama/llama_parse#47]
In the Parse -> 'Try demo' tab, I attempted to upload an 8.3mb PDF. The right panel immediately showed "Error parsing markdown" after I dropped the file into the target area in the browser window. When the upload eventually finished, it showed "Error during upload" and an error toast in the bottom right corner popped up showing "undefined\nundefined".

Perhaps there is a size limit on PDF uploads?

**Comment by anoopshrma** [comment]
Yes currently there is a size limit and page limit as well. Try passing a <250 pages pdf and it should work for you!

**Comment by BinaryBrain** [comment]
Since then, the size limit has been improved and we're working on a solution for even larger PDF.
