### ISSUE TITLE
How can I use the input_url parameter?

### ISSUE THREAD

**Issue by motoneurona** [run-llama/llama_parse#485]
I'm trying to use an URL as input. The website indicates that it is possible.

![image](https://github.com/user-attachments/assets/60ab96e6-e8c8-44e9-a2b6-c644b2d6a52e)

But I am not able to use that parameter. Am I missing something? Thank you.

**Comment by logan-markewich** [comment]
Added in latest release. `pip install -U llama-parse`

`parser.load_data(input_url)` or `parser.load_data([url1, url2])` or even mixing `parser.load_data([file_path, input_url])`

The URLs work best when pointing to direct files. Improvements to actual websites will come over time
