### ISSUE TITLE
Issue with LlamaParse ...

### ISSUE THREAD

**Issue by DhairyaMaradiya** [run-llama/llama_parse#486]
When calling the Llama Parse API using Python, there is no noticeable difference in performance or output when premium_mode is set to True compared to when it is set to False. However, in the Llama Index Playground, enabling premium_mode results in a noticeable improvement in parsing quality.

**Comment by marco-bertelli** [comment]
up here, maybe we are missing some settings in that, guys can you share the settings the playground is using to help us to better recreate that?
