### ISSUE TITLE
Unable to import Llama parse

### ISSUE THREAD

**Issue by AyushParikh** [run-llama/llama_parse#504]
**Describe the bug**
Write a concise description of what the bug is.

When we try to import Llama parse we get this error. Looks like pydantic v2.10 got released today and is breaking llama parse

```
[ERROR] PydanticSchemaGenerationError: Unable to generate pydantic-core schema for typing.AsyncGenerator[str, NoneType]. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
```

**Files**
If possible, please provide the PDF file causing the issue.

**Job ID**
If you have it, please provide the ID of the job you ran.
You can find it here: https://cloud.llamaindex.ai/parse in the "History" tab.

**Client:**
Please remove untested options:
 - Python Library
 - API
 - Frontend (cloud.llamaindex.ai)
 - Typescript Library
 - Notebook

**Additional context**
Add any additional context about the problem here.
What options did you use? Premium mode, multimodal, fast mode, parsing instructions, etc.
Screenshots, code snippets, etc.

**Comment by Disiok** [comment]
hey @AyushParikh ,

This is coming from pydantic v2.10 breaking `llama-index-core`.
We've updated to pin to an older version of pydantic. 
Can you try updating `llama-index-core` to the latest, and see if the issue persists?

**Comment by AyushParikh** [comment]
i have these in my req.txt file.

```llama_parse
llama-index
llama-index-readers-file==0.2.0
```

can you please provide me all the the latest version to resolve this?

**Comment by AyushParikh** [comment]
pip freeze

```
llama-cloud==0.1.5
llama-index==0.11.22
llama-index-agent-openai==0.3.4
llama-index-cli==0.3.1
llama-index-core==0.11.23
llama-index-embeddings-openai==0.2.5
llama-index-indices-managed-llama-cloud==0.6.0
llama-index-legacy==0.9.48.post4
llama-index-llms-openai==0.2.16
llama-index-multi-modal-llms-openai==0.2.3
llama-index-program-openai==0.2.0
llama-index-question-gen-openai==0.2.0
llama-index-readers-file==0.2.0
llama-index-readers-llama-parse==0.3.0
llama-parse==0.5.14
```

are these up to date?

**Comment by AyushParikh** [comment]
im still getting the issue.

**Comment by AyushParikh** [comment]
@Disiok

**Comment by AyushParikh** [comment]
ok works now.

**Comment by logan-markewich** [comment]
Yea, you'll need to ensure your installed version of pydantic is 2.9 or less -- sounds good!
