### ISSUE TITLE
Slower than usual. 

### ISSUE THREAD

**Issue by bsuttonvyde** [run-llama/llama_parse#507]
**Describe the bug**
Just slower than usual. 

**Files**
Not file specific, it's been slow on multiple files. 

**Job ID**
NA

**Client:**
NA

**Comment by BinaryBrain** [comment]
Hi @bsuttonvyde,
Can you give us more details? What mode are you using? What kind of files do you have (type, number of pages, etc.)?

**Comment by bsuttonvyde** [comment]
I'm using the default accurate mode. Bank statement files with approximately 5-15 pages each.

**Comment by bsuttonvyde** [comment]
I'm closing this issue because I do not expect a response, just wanted to notify you.
