### ISSUE TITLE
Information for source file name ...

### ISSUE THREAD

**Issue by wb200** [run-llama/llama_parse#51]
First up, great tool. Love using it and I'm getting very good usable results.

If possible, I'd like to request that the filename gets preserved, passed through in the parsing process and added to the metadata in the markdown output. The reason is that a lot of organizations (including mine) keep very orderly filename nomenclature. The name itself provides a lot of useful metadata that I need to make use of later on in the RAG pipeline. It would be a shame for it to be lost.

Hope this can be added. Or in case it's already available, please let me know how to access and retrieve the information. Think I inspected the output thoroughly but couldn't spot the original filenames post-parsing anywhere.

Cheers!

**Comment by anoopshrma** [comment]
I tried the API just now and I'm getting filename in the metadata. You can check it like this for metadata entries
```py 
for doc in documents:
     print(doc.metadata)
```
See if the filename is present for you or not

**Comment by BinaryBrain** [comment]
Closing this since it has been answered with no further comments.
