### ISSUE TITLE
Failed to parse the PDF file: Job failed: PDF_IS_PROTECTED

### ISSUE THREAD

**Issue by wb200** [run-llama/llama_parse#52]
Failed to parse the PDF file: Job failed: PDF_IS_PROTECTED

How can I find out which file in my directory caused this error? Would be great with "verbose=True" to tie the job_id to the actual file name that is being processed.

**Comment by horw** [comment]
Hello! I also find it quite important to see the file name. I have just created a PR for it. Perhaps the maintainer will merge it.
