### ISSUE TITLE
Module Not Found: Cannot Resolve '@llamaindex/readers/obsidian' in Next.js Build

### ISSUE THREAD

**Issue by Stroller15** [run-llama/llama_parse#521]
**Describe the bug**  
When building my project, I encounter the error:  
`Module not found: Can't resolve '@llamaindex/readers/obsidian'` in the file `index.js` in `node_modules/llamaindex/dist/readers/`. It appears that the `@llamaindex/readers/obsidian` module cannot be found.

**Files**  
I encountered this issue with a specific setup, but the error is not related to a PDF file. The issue is module resolution related.

**Job ID**  
Not applicable for this error as it pertains to a local build issue.

**Client:**  
- Frontend (cloud.llamaindex.ai)

**Additional context**  
- I am working in a Next.js environment (version 15.0.3 with Turbopack).
- The error occurred when attempting to import `@llamaindex/readers/obsidian`, but that module seems to be missing or incorrectly referenced in the package.
- No other issues with other readers like `mongo`, `notion`, or `pdf`.

**Screenshots/code snippets:**  
I am attaching a screenshot of the error for reference:  

<img width="945" alt="Screenshot 2024-12-02 at 2 45 04 PM" src="https://github.com/user-attachments/assets/f2b6f8d9-d875-476a-a701-3801ab0e8389">

**Comment by himself65** [comment]
Fixed in https://github.com/run-llama/LlamaIndexTS/commit/b8f0cbc4e056d9f0bcc3ec713e7faea72abfd1b3
