### ISSUE TITLE
Webhook never get send when parsing xlsx files

### ISSUE THREAD

**Issue by moMinosia** [run-llama/llama_parse#530]
**Describe the bug**
I never recieve a webhook answer after you finish parsing an xlsx file
First, it takes a long time to parse one, even though the file I tested is 44KB
Second, I waited for the initial webhook, nothing happened even though I can see it in your history tab 
And I sent the same file, so you didn't need to take that long to parse it since it's cached, and still no webhook

**Job ID**

- d09260c6-ee94-449f-bc93-2ae4bb4f4795
- 4bc2a79f-ff90-4d16-8504-70fd36056718

**Client:**
Please remove untested options:
 - API

**Comment by BinaryBrain** [comment]
Good catch @moMinosia!
A fix will be released next week.

**Comment by BinaryBrain** [comment]
Fixed in prod!
