### ISSUE TITLE
Figure parsing issue

### ISSUE THREAD

**Issue by dplutcho** [run-llama/llama_parse#54]
LammaParse did a great job of extraction for this entire PDF to markdown, however, was unable to fully extract Figure 2 on page 7. It's missing four of the five elements. https://www.veracode.com/sites/default/files/pdf/resources/analystreports/esg-research-insights-paper-veracode.pdf.

![image](https://github.com/run-llama/llama_parse/assets/3190399/97e0c5fe-ce4c-4d1a-a4c0-fd4adadbf217)

**Comment by Disiok** [comment]
Thanks for raising this. Hoping to improve the robustness in the next few releases!

**Comment by BinaryBrain** [comment]
I just tried to reproduce and could retrieve all figures in text and markdown. Please repoen if you face the issue again.
