### ISSUE TITLE
Import Issue : cannot import name 'LLM' from 'llama_index.core.llms'

### ISSUE THREAD

**Issue by chidhuAzh** [run-llama/llama_parse#556]
Im facing the issues

Version llama index : 0.9.48

 code 

import os
import nest_asyncio
from llama_parse import LlamaParse
from llama_index import SimpleDirectoryReader,VectorStoreIndex
from llama_index.core.tools import QueryEngineTool, ToolMetadata
from llama_index.core.query_engine import SubQuestionQueryEngine
from llama_index import LLMPredictor, ServiceContext

nest_asyncio.apply()

# Set LlamaParse API Key
parser = LlamaParse(
    api_key="llx-xTBOgT12R9wBAYwsosKcwvwU4t",
    result_type="markdown" 
)

# Set OpenAI API key
os.environ["OPENAI_API_KEY"] = "sk-mkJy0yPoH3dWfLBkA" # Replace with your OpenAI API key

pdf_directory = r"C:\Users\1919\Pictures\llama_check_files"

# Load and label documents from a single directory
def load_documents_from_directory(pdf_directory, parser):
    documents = []
    print("Loading documents from directory...")
    
    for file_name in os.listdir(pdf_directory):
        if file_name.endswith(".pdf"):
            file_path = os.path.join(pdf_directory, file_name)
            print(f"Processing file: {file_path}")

            reader = SimpleDirectoryReader(input_files=[file_path], file_extractor={".pdf": parser})
            pdf_documents = reader.load_data()

            for doc in pdf_documents:
                doc.metadata["file_name"] = file_name
            documents.extend(pdf_documents)

    print(f"Loaded {len(documents)} document(s).")
    return documents

# Create Query Engine
def create_query_engine(documents):
    print("Creating query engine...")
    # Create a vector store index
    vector_query_engine = VectorStoreIndex.from_documents(
        documents,
        use_async=True,
    ).as_query_engine()

    # Attach metadata to the query engine
    query_engine_tools = [
        QueryEngineTool(
            query_engine=vector_query_engine,
            metadata=ToolMetadata(
                name="medical_query_engine",
                description="Query engine for medical data extracted from PDFs.",
            ),
        ),
    ]

    # Create SubQuestionQueryEngine for advanced queries
    query_engine = SubQuestionQueryEngine.from_defaults(
        query_engine_tools=query_engine_tools,
        use_async=True,
    )
    print("Query engine is ready.")
    return query_engine

# Main execution
if __name__ == "__main__":
    print("Starting document processing...")

    # Step 1: Load documents from the single directory
    documents = load_documents_from_directory(pdf_directory, parser)

    # Step 2: Create query engine
    query_engine = create_query_engine(documents)

    # Step 3: Query the engine with a hardcoded query
    print("\nQuerying the medical data...")
    hardcoded_query = """
    You are an expert medical record analyst who gives detailed responses for user questions. 
    I have provided you medical data extracted from PDF documents.

    Question: Tell the patient name in the given records.
    """
    response = query_engine.query(hardcoded_query)
    print("\nQuery Response:")
    print(response)

**Comment by logan-markewich** [comment]
0.9.48 is nearly a year old though, i really recommend reading the docs and upgrading to the latest....
