### ISSUE TITLE
Premium mode is summarizing my documents instead of parsing them using API

### ISSUE THREAD

**Issue by DBTTB** [run-llama/llama_parse#558]
**Describe the bug**
Premium mode is summarizing my documents instead of parsing them when using API

**Files**
Multiple files.  Approximately 5 to 10% of the files parsed.

**Job ID**
Job id for reference:  8f8dd8c7-b8f6-4089-83ed-4c204af5100e

**Client:**
Please remove untested options:
 - Python Library - using python and API some files are summarized instead of parsed
 - API - using python and API some files are summarized instead of parsed
 - Frontend (cloud.llamaindex.ai) - works as expected

**Additional context**

parser = LlamaParse(
    api_key=os.environ.get('LLAMA_CLOUD_API_KEY'),
    result_type="markdown",
    num_workers=8,
    verbose=True,
    premium_mode=True,
    invalidate_cache=True,
    parsing_instruction="You are a highly proficient language model designed to convert pages from PDF into structured 
                                      markdown text.  The provided document contains multi-column data that includes tables and charts. 
                                      Your goal is to accurately transcribe all content strictly verbatim and maintain reading order.  Output 
                                      should be markdown formatted in an AI decipherable fashion. ",
    is_formatting_instruction=False,
    language="en",
)

**Comment by BinaryBrain** [comment]
Hi @DBTTB,
Thanks for providing the jobID of the failing job. Do you also have the jobID when sent from the frontend so I can compare them?

**Comment by DBTTB** [comment]
Here is the frontend job ID:  deb38638-fe49-4ce5-91eb-69e523576069

**Comment by DBTTB** [comment]
Retried the files with no parsing instructions and they were parsed successfully.
