### ISSUE TITLE
Could not extract json string from output error

### ISSUE THREAD

**Issue by bishwaTharu** [run-llama/llama_parse#56]
![error_llamaparse](https://github.com/run-llama/llama_parse/assets/71912170/d499c5d0-9f8c-41ef-ad2c-e79dee68f8e1)

I tried to use Ollama and got this issue while parsing the nodes.

**Comment by anoopshrma** [comment]
Yeah open-source llm are very reliable when it comes to parsing structured output.

**Comment by bishwaTharu** [comment]
Is there any way to fix the error? Any help is appreciated. @anoopshrma

**Comment by httplups** [comment]
Same problem here

**Comment by anoopshrma** [comment]
Open-source model requires good prompting to do what is told. And to make it return output in structured format is even harder. 

Llamaindex has done a compatibility testing on various factors for open-source llms in which pydantic output support is one of them.

You can take a look at the llms which works for structured formats and which not here: https://docs.llamaindex.ai/en/stable/module_guides/models/llms.html#open-source-llms
