### ISSUE TITLE
An unknown error occurred during processing. Job id: 80ebb07e-6996-4891-9293-a989d377bc4c

### ISSUE THREAD

**Issue by salman-khandu** [run-llama/llama_parse#563]
I was getting error like An unknown error occurred during processing. Job id: 80ebb07e-6996-4891-9293-a989d377bc4c with default mode. How can i know exact error detail?
Thank you

**Comment by BinaryBrain** [comment]
The error is due to a bug that can occur and we're working on it to fix it.
I suggest you add a retry mechanism in your code to send the job again on this particular error.

**Comment by salman-khandu** [comment]
does this kind of error will reduce credits that we got for per day?

**Comment by BinaryBrain** [comment]
No, we don't deduce credits when the job fail. You only get charged on successful jobs.
