### ISSUE TITLE
struggling to understand llama parse node based parser's benefits

### ISSUE THREAD

**Issue by MuhammedTech** [run-llama/llama_parse#565]
I’m struggling to understand Node based parser helps with the retrieval process. Even though there are PREVIOUS AND NEXT relationship attributes in each node, they are not included (encoded) when we do embeddings. Each node is parsed independently and doesn’t include explicit information about relationships like PREVIOUS or NEXT nodes when creating embeddings.

So my question is:

How does a node-based parser like LlamaParse improve retrieval if it doesn’t pass any relationship context (like PREVIOUS or NEXT) along with the node's content?
What’s the advantage of using a node-based structure for retrieval compared to using regular chunks of text without splitting it into nodes?
Is there an inherent benefit to node-based parsing in the retrieval pipeline, even if the relationships between nodes aren’t explicitly encoded in the embeddings?

I’d appreciate any insights into how node-based parsers can still be useful and improve retrieval effectiveness.

**Comment by logan-markewich** [comment]
Its just a way to maintain references to where that node was from when doing retrieval. Sometimes you might have an algorithm to grab neighbouring nodes, or maybe you need to re-assemble the entire document. This makes it possible.
