### ISSUE TITLE
Page numbers returned in response

### ISSUE THREAD

**Issue by stevelizcano** [run-llama/llama_parse#57]
For some indexing into our VectorDB, it's very helpful to know the page numbers if possible.

Is this feature possible now, or to add?

Either way, love the library. Great work!

**Comment by anoopshrma** [comment]
Currently page number is not returned in the metadata. But page content is separated using "-----------". You can separate the text based on the string pattern and provide page number for that by yourself. 


PS: Adding more info in metadata is being implemented and will be available soon.

**Comment by hexapode** [comment]
We will provide a more reliable way to get page number (JSON output) in a future release

**Comment by Laktus** [comment]
@hexapode When would such a release come? Until then is @anoopshrma suggestion a valid solution? Can we just replace each occurence of "-----------" with its respective page number? 

Would be nice if you could approve this @hexapode

**Comment by anoopshrma** [comment]
Hey @Laktus , json mode is out for quite some time now. 
You can give it a try: https://github.com/run-llama/llama_parse/blob/main/examples/demo_json_parsing.ipynb

**Comment by Laktus** [comment]
@anoopshrma Hi, is there also LlamaIndexTS support? Can i somewhere see a list of all supported modes? (Markdown, JSON, any more?). Thanks.

**Comment by salujav4** [comment]
Hey @Laktus, I am facing the same issue, I am using LlamaParseReader in typescript and I don't see the json format there, just text and markdown

**Comment by thisadev** [comment]
Hi, Can we get the page number using Python?

**Comment by aceci0127** [comment]
> You can now retrieve page numbers and other information using the Json output.
> 
> Using the API:
> 
> ```
> GET https://api.cloud.llamaindex.ai/api/parsing/job/<jobId>/result/json
> ```
> 
> Using the TS lib:
> 
> ```ts
> const reader = new LlamaParseReader({ resultType: "json" });
> const json = await reader.loadJson(path);
> ```

what is the JobID?

**Comment by BinaryBrain** [comment]
> Hi, Can we get the page number using Python?

Yes, if you get the Json results.

You can also use `{pageNumber}` in the [page separator](https://docs.cloud.llamaindex.ai/llamaparse/features/parsing_options#page-separator) and [page prefix and suffix](https://docs.cloud.llamaindex.ai/llamaparse/features/parsing_options#page-prefix-and-suffix)

> what is the JobID?

https://docs.cloud.llamaindex.ai/llamaparse/getting_started/api
Using the API, you first upload your file using `https://api.cloud.llamaindex.ai/api/parsing/upload` endpoint.
It'll return a jobID, and with the jobId, you can retrieve results.

**Comment by valter0009** [comment]
For me if I use `page_prefix` or `page_suffix` instead of `page_separator`, the output markdown file contains only first page of the document, anyone has the same problem?

**Comment by valter0009** [comment]
For me if I use `page_prefix `or `page_suffix` , the output markdown file contains only first page of the document, anyone has the same problem?
