### ISSUE TITLE
Missing values from table

### ISSUE THREAD

**Issue by CasKirch** [run-llama/llama_parse#63]
Trying to extract financial data but there seem to be missing values when using the preview. 
Markdown output:
![image](https://github.com/run-llama/llama_parse/assets/89792417/b61698b3-4037-4c6c-85b2-86b5ec79ff6a)

PDF page:
![image](https://github.com/run-llama/llama_parse/assets/89792417/e21b9053-e18a-48d5-8e4b-8205a655885e)

As indicated in the PDF page image, the file contains a total sum row of all 'Vlottende activa' (current assets) where the markdown representation of the page does not include this row.

**Comment by httplups** [comment]
I am having the same issue, I have a table that is big so it takes more than 1 page. The second part of the table is missing.

**Comment by BinaryBrain** [comment]
Should be fix with the latest API release
