### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'json'

### ISSUE THREAD

**Issue by Dr-Anil-Shinde** [run-llama/llama_parse#65]
%%time
from llama_parse import LlamaParse
documents = LlamaParse(result_type="markdown").load_data("uber_10q_march_2022.pdf")

Output--Started parsing the file under job_id c9d970f1-76ea-4fe2-89cc-859878869740
Error while parsing the PDF file 'uber_10q_march_2022.pdf': 'dict' object has no attribute 'json'

**Comment by Nayal17** [comment]
+1 . I got this error today, it was working fine a day back.

**Comment by Nayal17** [comment]
I am using colab notebook, any suggestion?
