### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'json'

### ISSUE THREAD

**Issue by Nayal17** [run-llama/llama_parse#67]
from llama_parse import LlamaParse
documents = LlamaParse(result_type="markdown").load_data("uber_10q_march_2022.pdf")

Output--Started parsing the file under job_id c9d970f1-76ea-4fe2-89cc-859878869740
Error while parsing the PDF file 'uber_10q_march_2022.pdf': 'dict' object has no attribute 'json'

I am using colab notebook, btw it was working fine a day back.

**Comment by jellchou** [comment]
Have a problem like that.

**Comment by mtsourma** [comment]
me too with python version 3.9

**Comment by MeTaNoV** [comment]
same, probably due to the introduction of the new `json` mode...

**Comment by logan-markewich** [comment]
@JungeAlexander @MeTaNoV @mtsourma @jellchou @Nayal17 

Fixed in v0.3.8
https://github.com/run-llama/llama_parse/pull/68
