### ISSUE TITLE
Invalid authentication token. Even with newly generated cloud API key.

### ISSUE THREAD

**Issue by ggjx22** [run-llama/llama_parse#71]
Hello Team, 

Really like your work on LlamaParse. The web app is working fine for PDF parsing but not the package.
Even when a new cloud API key is used, I got the same error.

```python
import nest_asyncio
nest_asyncio.apply()

from llama_parse import LlamaParse
import os
from dotenv import load_dotenv

load_dotenv()
LLAMA_CLOUD_API_KEY = os.getenv("LLAMA_PARSE_API")

parser = LlamaParse(api_key=LLAMA_CLOUD_API_KEY, result_type='markdown')

try:
    document = parser.load_data(file_path='data/file.pdf')
except Exception as error:
    print(f'An error occurred: {error}')
``` 
```
Error while parsing the PDF file 'data/filepdf': Failed to parse the PDF file: {"detail":"Invalid authentication token"}
An error occurred: Failed to parse the PDF file: {"detail":"Invalid authentication token"}
```

**Comment by anoopshrma** [comment]
Can you check if you are getting the correct API key from env.

**Comment by ggjx22** [comment]
Hmm I'm not sure what's going on. I switch to a Mac workstation with the exact piece of code in my issue above and the parser is working.

**Comment by anoopshrma** [comment]
I think it could be that env was not being picked correctly on your previous setup. Try printing it and check if it is getting correct API key or not.

**Comment by RaniBgz** [comment]
Bumping this because I am getting the same issue here.
Using a valid OpenAI key, initializing both in the environment as 'LLAMA_CLOUD_API_KEY', and passing it as a parameter to Llama Parse, but I get: 
```
    raise Exception(f"Failed to parse the PDF file: {response.text}")
Exception: Failed to parse the PDF file: {"detail":"Invalid authentication token"}
```
I am on Linux (Ubuntu), in a conda environment using Python 3.9.
The call to openAI models works with this api key.
In the tutorials, I also see the llama api key as looking like "llx...", whereas all of my keys from OpenAI start with "sk-...". Is there a different place to generate a llama key, or should a regular OpenAI key work?

Thanks for any info!

**Comment by anoopshrma** [comment]
LlamaCloud keys are totally different from openai keys! 

Llamacloud api keys are used to parse pdf files! 
You can generate one here: cloud.llamaindex.ai

**Comment by anoopshrma** [comment]
Sure no worries. Happy to help! Feel free to post any issue 💪

**Comment by me-jordankim** [comment]
I got an same error, but I solved this.

When I set `api_key={My OpenAI API key}` like the document said, I got an error.
Just change `api_key={My Llama cloud API key}`. then the problem will be solved.
(But I don't know why either. Maybe the document is wrong?)

**Comment by JeroCuevas** [comment]
It's because it doesn't work with LlamaCloud (EU), you need to change this.
