### ISSUE TITLE
Not Support to .doc extension

### ISSUE THREAD

**Issue by KP383** [run-llama/llama_parse#79]
When I install llama parser using pip then 
the list SUPPORTED_FILE_TYPES of base.py looks like
![image](https://github.com/run-llama/llama_parse/assets/79580721/42b63308-2818-41dc-9f71-54c44be962ab)
which gives error when i am dealing with .doc files
I suggest you to change the list with
SUPPORTED_FILE_TYPES = [
    ".pdf",
    ".xml",
    ".doc",
    ".docx",
    ".pptx",
    ".rtf",
    ".pages",
    ".key",
    ".epub"
]

**Comment by hexapode** [comment]
LlamaParse now support `.doc` files.
