### ISSUE TITLE
Where is the md file stored?

### ISSUE THREAD

**Issue by Ghostyboy0719** [run-llama/llama_parse#87]
I am trying to use the Llama_parse in google collab notebook to test it out. 

This is the code: 

import nest_asyncio
nest_asyncio.apply()

from llama_parse import LlamaParse

parser = LlamaParse(
    api_key="llx-my-API", 
    result_type="markdown",  
    num_workers=4, 
    verbose=True,
    language="en" 
)

# sync
documents = parser.load_data("./coding.pdf")

# sync batch
#documents = parser.load_data(["./my_file1.pdf", "./my_file2.pdf"])

# async
#documents = await parser.aload_data("./my_file.pdf")

# async batch
#documents = await parser.aload_data(["./my_file1.pdf", "./my_file2.pdf"])

It says that:  Started parsing the file under job_id <Long Job ID>

But where is the markdown file saved? Couldnt find it on the cloud nor in the collab notebook

**Comment by logan-markewich** [comment]
This just means that the parsing job has started on the remote server. Once its done, the function will return the parsed PDF files

**Comment by Ghostyboy0719** [comment]
> This just means that the parsing job has started on the remote server. Once its done, the function will return the parsed PDF files

Question is where will it return? Been a few hours and cannot find the md file on colab notebook or the cloud.

**Comment by logan-markewich** [comment]
In the variable you assign it to

For example
`documents = await parser.aload_data(["./my_file1.pdf", "./my_file2.pdf"])`

Here, it's in the documents variable. It may take a few minutes if it's a larger file, but it will either return or raise an error

**Comment by Ghostyboy0719** [comment]
OK will give this a try

**Comment by stockcoder** [comment]
> In the variable you assign it to
> 
> For example `documents = await parser.aload_data(["./my_file1.pdf", "./my_file2.pdf"])`
> 
> Here, it's in the documents variable. It may take a few minutes if it's a larger file, but it will either return or raise an error

I want to know how to save the markdown files to my disk? Can you give me some code?

**Comment by logan-markewich** [comment]
@stockcoder it's just like writing normal text to a file?

```
documents = reader.load_data("file.pdf")

with open("file.md", "w") as f.
  f.write(documents[0].text)

```

Here I only loaded one file, so the list of documents returned only has one item.
