### ISSUE TITLE
Tables Not Parsing Properly 

### ISSUE THREAD

**Issue by vikas351** [run-llama/llama_parse#90]
I have a table,the table is not parsing properly,its missing one of the main column 

Source Image:
<img width="888" alt="image-20240304-122143" src="https://github.com/run-llama/llama_parse/assets/30958995/a5cdfc5f-3fa8-4449-bbc4-a7f8360d1916">

its parsing like this:

|Valuation Inputs|Level 2 Other|Total Market Value at 10/31/22|
|---|---|---|
|Level 1 Quoted Prices|Significant Observable Inputs| |
|INVESTMENTS IN SECURITIES:| | |
|ASSETS (Market Value):| | |
|Common Stocks| | |
|Financial Services|$294,480|$29,700|$324,180|
|Other Industries (a)|$2,825,497| |$2,825,497|
|Total Common Stocks|$3,119,977|$29,700|$3,149,677|
|Preferred Stocks (a)|$36,165| |$36,165|
|Rights (a)| |$100|$100|
|Warrants (a)|$86| |$86|
|U.S. Government Obligations| |$1,338,806|$1,338,806|
|TOTAL INVESTMENTS IN SECURITIES – ASSETS|$3,156,228|$1,368,606|$4,524,834|

**Comment by hexapode** [comment]
Could you share the page of the document this table is extract from?

**Comment by vikas351** [comment]
[test.pdf](https://github.com/run-llama/llama_parse/files/14639273/test.pdf)

**Comment by BinaryBrain** [comment]
Should be fix with the latest API release
