### ISSUE TITLE
No result (NO_CONTENT_HERE)

### ISSUE THREAD

**Issue by jwpark1985** [run-llama/llama_parse#92]
Hello, 
After installing the new version (v0.10.40), I see many NO_CONTENT_HERE results with the pdf files, which have contents (about 10% of the documents returns NO_CONTENT_HERE).

The sampled documents are here: [pdf1](https://drive.google.com/file/d/1ExKtekqYHGLOVQ416CfFiPZrLJPd1KVa/view?usp=sharing), [pdf2](https://drive.google.com/file/d/1F1xxPLlGTo2Ci0e5_tAVSe2uMQ6hRvAp/view?usp=sharing), [pdf3](https://drive.google.com/file/d/10lfqnDt0Tb1Qg49VtchrB0H3UZuRac1g/view?usp=sharing), [pdf4](https://drive.google.com/file/d/1Q4PSUQ5qzY3kLLi5688RomP9kcQQUlXn/view?usp=sharing).

This is the code that I used:

```
parser = LlamaParse(
    api_key=LLAMA_CLOUD_API_KEY,  # can also be set in your env as LLAMA_CLOUD_API_KEY
    result_type="markdown",  # "markdown" and "text" are available
    num_workers=1, # if multiple files passed, split in `num_workers` API calls
    verbose=True,
    language="en" 
)

documents = parser.load_data(inputs) # inputs are the documents stored in my local storage
```

**Comment by solanpaa** [comment]
I see the same with long files, e.g.,  https://data.consilium.europa.eu/doc/document/ST-5662-2024-INIT/en/pdf.

But when I extract only a few pages and submit those, then it parses fine.

**Comment by jwpark1985** [comment]
Thanks, Solanpaa. It makes sense for you case. However, because the above pdf files are 1-page document, I can't reduce the amount of pages.

**Comment by jwpark1985** [comment]
From yesterday, I could get results correctly (maybe version update?). I close this issue.
