### ISSUE TITLE
Textract result in blog post

### ISSUE THREAD

**Issue by ThomasDelteil** [run-llama/llama_parse#94]
![image](https://github.com/run-llama/llama_parse/assets/3716307/07f1f363-9a15-44b2-90f9-9ee5afb9c4ec)

I am curious about what the red highlight mean on this picture and notably for Textract. The output of the textract API is (near)-perfect on that document, so I am wondering where the degradation might come from.

![Screenshot 2024-03-18 at 16 36 14](https://github.com/run-llama/llama_parse/assets/3716307/ea4cd72b-ea46-4aa8-ad54-53d65c1ffab4)

You might want to check some of the document to text approaches we have made available through our textractor client library in case they are useful:
 
https://aws-samples.github.io/amazon-textract-textractor/notebooks/document_linearization_to_markdown_or_html.html 
https://aws-samples.github.io/amazon-textract-textractor/notebooks/textractor_for_large_language_models.html
https://aws-samples.github.io/amazon-textract-textractor/notebooks/tabular_data_linearization.html

thanks,

(disclaimer: I work on Textract table recognition)

**Comment by hexapode** [comment]
I believe we are using https://textract.readthedocs.io/en/stable/ not AWS Textract, we should made it more clear.
